/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gov.cdc.dataingestion.hl7.parser;

import ca.uhn.hl7v2.DefaultHapiContext;
import ca.uhn.hl7v2.HL7Exception;
import gov.cdc.dataingestion.hl7.parser.integration.Hl7Parser;
import gov.cdc.dataingestion.hl7.parser.integration.interfaces.IHl7Parser;
import gov.cdc.dataingestion.hl7.parser.model.Hl7ParsedMessage;

public class HL7ParserLibrary {

    private IHl7Parser parser = new Hl7Parser(new DefaultHapiContext());
    public boolean someLibraryMethod() {
        return true;
    }

    public String hl7StringValidation(String message) throws HL7Exception {
        return parser.hl7MessageStringValidation(message);
    }

    public Hl7ParsedMessage hl7StringParser(String message) throws HL7Exception {
        return parser.hl7StringParser(message);
    }
}
