SELECT MSG_CONTAINER_UID, PLA_LOCAL_ID, PLA_AUTHOR_ID, PLA_EFFECTIVE_TIME,
       PLA_ADDR_AS_OF_DT, PLA_ADDR_CITY_TXT, PLA_ADDR_COUNTY_CD
        , PLA_ADDR_COUNTRY_CD, PLA_ADDR_STATE_CD, PLA_ADDR_STREET_ADDR1_TXT, PLA_ADDR_STREET_ADDR2_TXT,
       PLA_ADDR_ZIP_CODE_TXT, PLA_ADDR_COMMENT_TXT, PLA_CENSUS_TRACT_TXT, PLA_COMMENT_TXT
        , PLA_EMAIL_ADDRESS_TXT, PLA_ID_QUICK_CODE, PLA_NAME_TXT, PLA_PHONE_AS_OF_DT,
       PLA_PHONE_COUNTRY_CODE_TXT, PLA_PHONE_EXTENSION_TXT, PLA_PHONE_NBR_TXT, PLA_PHONE_COMMENT_TXT
        , PLA_TYPE_CD, PLA_URL_ADDRESS_TXT FROM dbo.MSG_PLACE where MSG_CONTAINER_UID=:MSG_CONTAINER_UID