SELECT MSG_EVENT_ID
     ,MSG_EVENT_TYPE
     ,ANSWER_TXT
     ,ANSWER_LARGE_TXT
     ,ANSWER_GROUP_SEQ_NBR
     ,PART_TYPE_CD
     ,QUESTION_IDENTIFIER
     ,QUESTION_GROUP_SEQ_NBR
     ,SEQ_NBR
FROM  MSG_ANSWER where PART_TYPE_CD is not null and MSG_EVENT_ID =:INV_LOCAL_ID and MSG_EVENT_TYPE
    = 'CASE' AND MSG_CONTAINER_UID=:MSG_CONTAINER_UID
                   AND  MSG_ANSWER.QUESTION_GROUP_SEQ_NBR  IS NULL