SELECT
    DISTINCT MSG_ANSWER.QUESTION_GROUP_SEQ_NBR,MSG_ANSWER.ANSWER_GROUP_SEQ_NBR,MSG_ANSWER.SEQ_NBR,
             MSG_QUESTION_LOOKUP.DATA_TYPE, MSG_ANSWER.QUESTION_IDENTIFIER,
             MSG_ANSWER.MSG_CONTAINER_UID, MSG_ANSWER.MSG_EVENT_ID,
             MSG_ANSWER.MSG_EVENT_TYPE, MSG_ANSWER.ANS_CODE_SYSTEM_CD,
             MSG_ANSWER.ANS_CODE_SYSTEM_DESC_TXT, MSG_ANSWER.ANS_DISPLAY_TXT, MSG_ANSWER.ANSWER_TXT,
             MSG_ANSWER.PART_TYPE_CD, MSG_ANSWER.QUES_CODE_SYSTEM_CD,
             MSG_QUESTION_LOOKUP.QUES_CODE_SYSTEM_DESC_TXT,
             MSG_ANSWER.QUES_DISPLAY_TXT,
             MSG_QUESTION_LOOKUP.QUESTION_DISPLAY_NAME, MSG_ANSWER_LOOKUP.ANS_TO_CODE,
             MSG_ANSWER_LOOKUP.ANS_TO_CODE_SYSTEM_CD,
             MSG_ANSWER_LOOKUP.ANS_TO_DISPLAY_NM, MSG_ANSWER_LOOKUP.CODE_TRANSLATION_REQUIRED,
             MSG_ANSWER_LOOKUP.ANS_TO_CODE_SYSTEM_DESC_TXT
FROM   MSG_ANSWER INNER JOIN
       MSG_QUESTION_LOOKUP ON MSG_ANSWER.QUESTION_IDENTIFIER =
                              MSG_QUESTION_LOOKUP.QUESTION_IDENTIFIER AND
                              MSG_ANSWER.QUES_CODE_SYSTEM_CD = MSG_QUESTION_LOOKUP.QUES_CODE_SYSTEM_CD LEFT OUTER  JOIN
       MSG_ANSWER_LOOKUP ON MSG_ANSWER.QUESTION_IDENTIFIER =
                            MSG_ANSWER_LOOKUP.QUESTION_IDENTIFIER AND
                            MSG_ANSWER.QUES_CODE_SYSTEM_CD = MSG_ANSWER_LOOKUP.QUES_CODE_SYSTEM_CD AND
                            MSG_ANSWER.ANSWER_TXT = MSG_ANSWER_LOOKUP.ANS_FROM_CODE AND
                            MSG_ANSWER.ANS_CODE_SYSTEM_CD = MSG_ANSWER_LOOKUP.ANS_FROM_CODE_SYSTEM_CD
WHERE PART_TYPE_CD IS NULL AND MSG_CONTAINER_UID = :MSG_CONTAINER_UID and MSG_EVENT_ID = :INV_LOCAL_ID
  and  MSG_EVENT_TYPE = 'CASE'  and MSG_ANSWER.QUESTION_GROUP_SEQ_NBR  IS NULL
  and  MSG_QUESTION_LOOKUP.DATA_TYPE not  IN ('XML')
  AND DATA_TYPE <> 'COUNTY'
UNION
SELECT
    DISTINCT MSG_ANSWER.QUESTION_GROUP_SEQ_NBR,MSG_ANSWER.ANSWER_GROUP_SEQ_NBR,MSG_ANSWER.SEQ_NBR,
             'CODED' AS DATA_TYPE, MSG_ANSWER.QUESTION_IDENTIFIER,
             MSG_ANSWER.MSG_CONTAINER_UID, MSG_ANSWER.MSG_EVENT_ID,
             MSG_ANSWER.MSG_EVENT_TYPE, MSG_ANSWER.ANS_CODE_SYSTEM_CD,
             MSG_ANSWER.ANS_CODE_SYSTEM_DESC_TXT, MSG_ANSWER.ANS_DISPLAY_TXT, MSG_ANSWER.ANSWER_TXT,
             MSG_ANSWER.PART_TYPE_CD, MSG_ANSWER.QUES_CODE_SYSTEM_CD,
             MSG_ANSWER.QUES_CODE_SYSTEM_DESC_TXT, MSG_ANSWER.QUES_DISPLAY_TXT,
             MSG_ANSWER.QUES_DISPLAY_TXT AS  QUESTION_DISPLAY_NAME, MSG_ANSWER_LOOKUP.ANS_TO_CODE,
             MSG_ANSWER_LOOKUP.ANS_TO_CODE_SYSTEM_CD, MSG_ANSWER_LOOKUP.ANS_TO_DISPLAY_NM,
             MSG_ANSWER_LOOKUP.CODE_TRANSLATION_REQUIRED, MSG_ANSWER_LOOKUP.ANS_TO_CODE_SYSTEM_DESC_TXT
FROM   MSG_ANSWER
           INNER  JOIN MSG_ANSWER_LOOKUP ON MSG_ANSWER_LOOKUP.QUESTION_IDENTIFIER = 'COUNTY'
    AND          MSG_ANSWER.QUES_CODE_SYSTEM_CD = MSG_ANSWER_LOOKUP.QUES_CODE_SYSTEM_CD
    AND			 MSG_ANSWER.ANSWER_TXT = MSG_ANSWER_LOOKUP.ANS_FROM_CODE
    AND          MSG_ANSWER.ANS_CODE_SYSTEM_CD = MSG_ANSWER_LOOKUP.ANS_FROM_CODE_SYSTEM_CD
WHERE PART_TYPE_CD IS NULL AND MSG_CONTAINER_UID = :MSG_CONTAINER_UID and MSG_EVENT_ID = :INV_LOCAL_ID
  AND  MSG_EVENT_TYPE = 'CASE'  AND MSG_ANSWER.QUESTION_GROUP_SEQ_NBR  IS NULL
  AND MSG_ANSWER.QUES_DISPLAY_TXT IS NOT NULL
ORDER BY
    MSG_ANSWER.QUESTION_GROUP_SEQ_NBR,MSG_ANSWER.ANSWER_GROUP_SEQ_NBR,MSG_ANSWER.QUESTION_IDENTIFIER,MSG_ANSWER.SEQ_NBR