SELECT TRT_LOCAL_ID,TRT_AUTHOR_ID,TRT_COMPOSITE_CD,TRT_COMMENT_TXT
     ,TRT_CUSTOM_TREATMENT_TXT,TRT_DOSAGE_AMT,TRT_DOSAGE_UNIT_CD,TRT_DRUG_CD
     ,TRT_DURATION_AMT,TRT_DURATION_UNIT_CD,TRT_EFFECTIVE_TIME,TRT_FREQUENCY_AMT_CD
     ,TRT_ROUTE_CD,TRT_TREATMENT_DT FROM MSG_TREATMENT WHERE MSG_CONTAINER_UID = :MSG_CONTAINER_UID