SELECT 'XML' AS DATA_TYPE, MSG_ANSWER.ANSWER_XML_TXT
from MSG_ANSWER where MSG_CONTAINER_UID =:MSG_CONTAINER_UID and MSG_EVENT_ID = :INV_LOCAL_ID
                  and  MSG_EVENT_TYPE = 'CASE'  and MSG_ANSWER.ANSWER_XML_TXT  IS NOT NULL
ORDER BY
    MSG_ANSWER.QUESTION_GROUP_SEQ_NBR,MSG_ANSWER.ANSWER_GROUP_SEQ_NBR,MSG_ANSWER.QUESTION_IDENTIFIER,MSG_ANSWER.SEQ_NBR