services:
  report-service:
    build:
      context: ./
      dockerfile: ./report-service/Dockerfile
    container_name: report-service
    env_file:
      - dataingestion.env
    networks:
      - dataingestion
networks:
  dataingestion:
      name: dataingestion