services:
  data-ingestion-service:
    build:
      context: ./
      dockerfile: ./data-ingestion-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - broker
      - di-mssql
      - keycloak
    container_name: data-ingestion-service
    env_file:
      - dataingestion.env
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: broker:29092
    networks:
      - dataingestion

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dataingestion

  broker:
    image: confluentinc/cp-kafka:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: 'INTERNAL://broker:29092,EXTERNAL://broker:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    networks:
      - dataingestion

  di-mssql:
    build: 
      context: ./containers/db
      args:
          - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    container_name: di-mssql
    ports:
      - 2433:1433
    environment:
      - ACCEPT_EULA=1
      - SQLCMDPASSWORD=${DATABASE_PASSWORD}
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dataingestion

  keycloak:
    container_name: di-keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8100:8080"
    volumes:
      - ./containers/keycloak/imports:/opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"
    networks:
      - dataingestion

networks:
  dataingestion:
    name: dataingestion
