INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (1,'82306-2',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (2,'80364-3','Chlamydia trachomatis rRNA [Presence] in Rectum by Probe and target amplification method (80364-3)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (3,'6920-3',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (4,'6919-5',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (5,'6349-5',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (6,'57288-3',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (7,'57287-5',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (8,'53926-2',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (9,'53925-4',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (10,'50411-8',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (11,'50387-0','Chlamydia trachomatis rRNA [Presence] in Cervix by Probe and target amplification method (50387-0)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (12,'45001-5',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (13,'43304-5','Chlamydia trachomatis rRNA [Presence] in Unspecified specimen by Probe and target amplification method (43304-5)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (14,'42931-6','Chlamydia trachomatis rRNA [Presence] in Urine by Probe and target amplification method (42931-6)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (15,'38347-1','XXX microorganism DNA [Identifier] in Unspecified specimen by Probe and target amplification method (38347-1)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (16,'36902-5','Chlamydia trachomatis+Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and target amplification method (36902-5)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (17,'35729-3','Chlamydia sp DNA [Presence] in Unspecified specimen by Probe and target amplification method (35729-3)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (18,'35713-7',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (19,'34708-8','Chlamydia sp DNA [Presence] in Urine by Probe and target amplification method (34708-8)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (20,'32774-2','Chlamydia sp DNA [Presence] in Genital specimen by Probe and target amplification method (32774-2)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (21,'21613-5','Chlamydia trachomatis DNA [Presence] in Unspecified specimen by Probe and target amplification method (21613-5)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (22,'21190-4','Chlamydia trachomatis DNA [Presence] in Cervix by Probe and target amplification method (21190-4)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (23,'11475-1',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (24,'10352-3',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (25,'24111-7','Neisseria gonorrhoeae DNA [Presence] in Unspecified specimen by Probe and target amplification method (24111-7)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (26,'32367-5',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (27,'CGPCR',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (28,'77577-5',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (29,'43305-2','Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen by Probe and target amplification method (43305-2)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (30,'47387-6','Neisseria gonorrhoeae DNA [Presence] in Genital specimen by Probe and target amplification method (47387-6)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (31,'5028-6','Neisseria gonorrhoeae rRNA [Presence] in Unspecified specimen by DNA probe (5028-6)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (32,'50388-8','Neisseria gonorrhoeae rRNA [Presence] in Cervix by Probe and target amplification method (50388-8)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (33,'53879-3','Neisseria gonorrhoeae rRNA [Presence] in Vaginal fluid by Probe and target amplification method (53879-3)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (34,'53927-0','Neisseria gonorrhoeae rRNA [Presence] in Urethra by Probe and target amplification method (53927-0)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (35,'57458-2','Neisseria gonorrhoeae rRNA [Presence] in Anal by Probe and target amplification method (57458-2)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (36,'60255-7',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (37,'60256-5','Neisseria gonorrhoeae rRNA [Presence] in Urine by Probe and target amplification method (60256-5)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (38,'611-4',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (39,'626-2',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (40,'630-4',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (41,'634-6',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (42,'6462-6',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (43,'6463-4',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (44,'698-1',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (45,'80366-8','Neisseria gonorrhoeae rRNA [Presence] in Rectum by Probe and target amplification method (80366-8)');
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (46,'aerBact ID',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (47,'aerBact ID_R',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (48,'GC Iso',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (49,'Gonorrhea',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (50,'Chlamydia',NULL);
INSERT INTO obx_id_std_lookup(UID,OBX_VALUE_TYPE_ID,OBX_VALUE_TYPE_DESC) VALUES (51,'chlamiso',NULL);