rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
server:
  port: 8083
app:
  security:
    username: admin
    password: password
spring:
  application:
    name: report-service

logging:
  #  Only one config can be active at a time
  config: classpath:dlt-logback.xml
  pattern:
    console: "%d %-5level %logger : %file-%line : %msg%n"
    file:    "%d %-5level [%thread] %logger : [ramesh] : %msg%n"
    
  level:
    com.apps.restfulApp.api.controller: ERROR
  file:
    name: logs/report-service.log

---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:sqlserver://${DI_DBSERVER};databaseName=${DI_DBNAME};encrypt=true;trustServerCertificate=true;
    username: ${DI_USERNAME}
    password: ${DI_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    nbs:
      url: jdbc:sqlserver://${DI_NBS_DBSERVER};databaseName=${DI_NBS_DBNAME};encrypt=true;trustServerCertificate=true;
      username: ${DI_NBS_DBUSER}
      password: ${DI_NBS_DBPASSWORD}
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    group-id: data-ingestion-group
    consumer:
      maxPollIntervalMs: 30000

kafka:
  consumer:
    max-retry: 2
  raw:
    producer:
      topic: elr_raw
    topic: elr_raw
  validation:
    topic: elr_validated
  fhir-conversion:
    topic: fhir_converted
  fhir-conversion-prep:
    topic: fhir_prep
  xml-conversion:
    topic: xml_converted
  xml-conversion-prep:
    topic: xml_prep
  elr-duplicate:
    topic: elr_duplicate
  topics: elr_raw,elr_validated
  retry:
      suffix: _retry
  dlt:
      suffix: _dlt

---
spring:
  config:
    activate:
      on-profile: kubernetes

  datasource:
    url: db_di_url
    username: db_di_username
    password: db_di_password
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

    nbs:
      url: db_nbs_url
      username: db_nbs_username
      password: db_nbs_password
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: kafka_bootstrap_servers
    group-id: data-ingestion-group
    consumer:
      maxPollIntervalMs: 30000

kafka:
  consumer:
    max-retry: 2
  raw:
    producer:
      topic: elr_raw
    topic: elr_raw
  validation:
    topic: elr_validated
  fhir-conversion:
    topic: fhir_converted
  fhir-conversion-prep:
    topic: fhir_prep
  xml-conversion:
    topic: xml_converted
  xml-conversion-prep:
    topic: xml_prep
  elr-duplicate:
    topic: elr_duplicate
  topics: elr_raw,elr_validated
  retry:
    suffix: _retry
  dlt:
    suffix: _dlt
