package gov.cdc.dataprocessing.repository.nbs.odse.model;


import gov.cdc.dataprocessing.repository.nbs.odse.model.observation.ObservationBase;
import org.junit.jupiter.api.Test;

import java.sql.Timestamp;

import static org.junit.jupiter.api.Assertions.*;

class ObservationBaseTest {

    @Test
    void testDefaultConstructor() {
        // Arrange & Act
        ObservationBase observation = new ObservationBase();

        // Assert
        assertNull(observation.getObservationUid());
        assertNull(observation.getActivityDurationAmt());
        assertNull(observation.getActivityDurationUnitCd());
        assertNull(observation.getActivityFromTime());
        assertNull(observation.getActivityToTime());
        assertNull(observation.getAddReasonCd());
        assertNull(observation.getAddTime());
        assertNull(observation.getAddUserId());
        assertNull(observation.getCd());
        assertNull(observation.getCdDescTxt());
        assertNull(observation.getCdSystemCd());
        assertNull(observation.getCdSystemDescTxt());
        assertNull(observation.getConfidentialityCd());
        assertNull(observation.getConfidentialityDescTxt());
        assertNull(observation.getCtrlCdDisplayForm());
        assertNull(observation.getCtrlCdUserDefined1());
        assertNull(observation.getCtrlCdUserDefined2());
        assertNull(observation.getCtrlCdUserDefined3());
        assertNull(observation.getCtrlCdUserDefined4());
        assertNull(observation.getDerivationExp());
        assertNull(observation.getEffectiveDurationAmt());
        assertNull(observation.getEffectiveDurationUnitCd());
        assertNull(observation.getEffectiveFromTime());
        assertNull(observation.getEffectiveToTime());
        assertNull(observation.getElectronicInd());
        assertNull(observation.getGroupLevelCd());
        assertNull(observation.getJurisdictionCd());
        assertNull(observation.getLabConditionCd());
        assertNull(observation.getLastChgReasonCd());
        assertNull(observation.getLastChgTime());
        assertNull(observation.getLastChgUserId());
        assertNull(observation.getLocalId());
        assertNull(observation.getMethodCd());
        assertNull(observation.getMethodDescTxt());
        assertNull(observation.getObsDomainCd());
        assertNull(observation.getObsDomainCdSt1());
        assertNull(observation.getPnuCd());
        assertNull(observation.getPriorityCd());
        assertNull(observation.getPriorityDescTxt());
        assertNull(observation.getProgAreaCd());
        assertNull(observation.getRecordStatusCd());
        assertNull(observation.getRecordStatusTime());
        assertNull(observation.getRepeatNbr());
        assertNull(observation.getStatusCd());
        assertNull(observation.getStatusTime());
        assertNull(observation.getSubjectPersonUid());
        assertNull(observation.getTargetSiteCd());
        assertNull(observation.getTargetSiteDescTxt());
        assertNull(observation.getTxt());
        assertNull(observation.getUserAffiliationTxt());
        assertNull(observation.getValueCd());
        assertNull(observation.getYnuCd());
        assertNull(observation.getProgramJurisdictionOid());
        assertNull(observation.getSharedInd());
        assertNull(observation.getVersionCtrlNbr());
        assertNull(observation.getAltCd());
        assertNull(observation.getAltCdDescTxt());
        assertNull(observation.getAltCdSystemCd());
        assertNull(observation.getAltCdSystemDescTxt());
        assertNull(observation.getCdDerivedInd());
        assertNull(observation.getRptToStateTime());
        assertNull(observation.getCdVersion());
        assertNull(observation.getProcessingDecisionCd());
        assertNull(observation.getPregnantIndCd());
        assertNull(observation.getPregnantWeek());
        assertNull(observation.getProcessingDecisionTxt());
    }

    @Test
    void testSettersAndGetters() {
        // Arrange
        ObservationBase observation = new ObservationBase();

        Long observationUid = 1L;
        String activityDurationAmt = "durationAmt";
        String activityDurationUnitCd = "durationUnitCd";
        Timestamp activityFromTime = new Timestamp(System.currentTimeMillis());
        Timestamp activityToTime = new Timestamp(System.currentTimeMillis());
        String addReasonCd = "reasonCd";
        Timestamp addTime = new Timestamp(System.currentTimeMillis());
        Long addUserId = 2L;
        String cd = "cd";
        String cdDescTxt = "cdDescTxt";
        String cdSystemCd = "cdSystemCd";
        String cdSystemDescTxt = "cdSystemDescTxt";
        String confidentialityCd = "confidentialityCd";
        String confidentialityDescTxt = "confidentialityDescTxt";
        String ctrlCdDisplayForm = "ctrlCdDisplayForm";
        String ctrlCdUserDefined1 = "ctrlCdUserDefined1";
        String ctrlCdUserDefined2 = "ctrlCdUserDefined2";
        String ctrlCdUserDefined3 = "ctrlCdUserDefined3";
        String ctrlCdUserDefined4 = "ctrlCdUserDefined4";
        Integer derivationExp = 3;
        String effectiveDurationAmt = "effectiveDurationAmt";
        String effectiveDurationUnitCd = "effectiveDurationUnitCd";
        Timestamp effectiveFromTime = new Timestamp(System.currentTimeMillis());
        Timestamp effectiveToTime = new Timestamp(System.currentTimeMillis());
        String electronicInd = "electronicInd";
        String groupLevelCd = "groupLevelCd";
        String jurisdictionCd = "jurisdictionCd";
        String labConditionCd = "labConditionCd";
        String lastChgReasonCd = "lastChgReasonCd";
        Timestamp lastChgTime = new Timestamp(System.currentTimeMillis());
        Long lastChgUserId = 4L;
        String localId = "localId";
        String methodCd = "methodCd";
        String methodDescTxt = "methodDescTxt";
        String obsDomainCd = "obsDomainCd";
        String obsDomainCdSt1 = "obsDomainCdSt1";
        String pnuCd = "pnuCd";
        String priorityCd = "priorityCd";
        String priorityDescTxt = "priorityDescTxt";
        String progAreaCd = "progAreaCd";
        String recordStatusCd = "recordStatusCd";
        Timestamp recordStatusTime = new Timestamp(System.currentTimeMillis());
        Integer repeatNbr = 5;
        String statusCd = "statusCd";
        Timestamp statusTime = new Timestamp(System.currentTimeMillis());
        Long subjectPersonUid = 6L;
        String targetSiteCd = "targetSiteCd";
        String targetSiteDescTxt = "targetSiteDescTxt";
        String txt = "txt";
        String userAffiliationTxt = "userAffiliationTxt";
        String valueCd = "valueCd";
        String ynuCd = "ynuCd";
        Long programJurisdictionOid = 7L;
        String sharedInd = "Y";
        Integer versionCtrlNbr = 1;
        String altCd = "altCd";
        String altCdDescTxt = "altCdDescTxt";
        String altCdSystemCd = "altCdSystemCd";
        String altCdSystemDescTxt = "altCdSystemDescTxt";
        String cdDerivedInd = "cdDerivedInd";
        Timestamp rptToStateTime = new Timestamp(System.currentTimeMillis());
        String cdVersion = "cdVersion";
        String processingDecisionCd = "processingDecisionCd";
        String pregnantIndCd = "pregnantIndCd";
        Integer pregnantWeek = 10;
        String processingDecisionTxt = "processingDecisionTxt";

        // Act
        observation.setObservationUid(observationUid);
        observation.setActivityDurationAmt(activityDurationAmt);
        observation.setActivityDurationUnitCd(activityDurationUnitCd);
        observation.setActivityFromTime(activityFromTime);
        observation.setActivityToTime(activityToTime);
        observation.setAddReasonCd(addReasonCd);
        observation.setAddTime(addTime);
        observation.setAddUserId(addUserId);
        observation.setCd(cd);
        observation.setCdDescTxt(cdDescTxt);
        observation.setCdSystemCd(cdSystemCd);
        observation.setCdSystemDescTxt(cdSystemDescTxt);
        observation.setConfidentialityCd(confidentialityCd);
        observation.setConfidentialityDescTxt(confidentialityDescTxt);
        observation.setCtrlCdDisplayForm(ctrlCdDisplayForm);
        observation.setCtrlCdUserDefined1(ctrlCdUserDefined1);
        observation.setCtrlCdUserDefined2(ctrlCdUserDefined2);
        observation.setCtrlCdUserDefined3(ctrlCdUserDefined3);
        observation.setCtrlCdUserDefined4(ctrlCdUserDefined4);
        observation.setDerivationExp(derivationExp);
        observation.setEffectiveDurationAmt(effectiveDurationAmt);
        observation.setEffectiveDurationUnitCd(effectiveDurationUnitCd);
        observation.setEffectiveFromTime(effectiveFromTime);
        observation.setEffectiveToTime(effectiveToTime);
        observation.setElectronicInd(electronicInd);
        observation.setGroupLevelCd(groupLevelCd);
        observation.setJurisdictionCd(jurisdictionCd);
        observation.setLabConditionCd(labConditionCd);
        observation.setLastChgReasonCd(lastChgReasonCd);
        observation.setLastChgTime(lastChgTime);
        observation.setLastChgUserId(lastChgUserId);
        observation.setLocalId(localId);
        observation.setMethodCd(methodCd);
        observation.setMethodDescTxt(methodDescTxt);
        observation.setObsDomainCd(obsDomainCd);
        observation.setObsDomainCdSt1(obsDomainCdSt1);
        observation.setPnuCd(pnuCd);
        observation.setPriorityCd(priorityCd);
        observation.setPriorityDescTxt(priorityDescTxt);
        observation.setProgAreaCd(progAreaCd);
        observation.setRecordStatusCd(recordStatusCd);
        observation.setRecordStatusTime(recordStatusTime);
        observation.setRepeatNbr(repeatNbr);
        observation.setStatusCd(statusCd);
        observation.setStatusTime(statusTime);
        observation.setSubjectPersonUid(subjectPersonUid);
        observation.setTargetSiteCd(targetSiteCd);
        observation.setTargetSiteDescTxt(targetSiteDescTxt);
        observation.setTxt(txt);
        observation.setUserAffiliationTxt(userAffiliationTxt);
        observation.setValueCd(valueCd);
        observation.setYnuCd(ynuCd);
        observation.setProgramJurisdictionOid(programJurisdictionOid);
        observation.setSharedInd(sharedInd);
        observation.setVersionCtrlNbr(versionCtrlNbr);
        observation.setAltCd(altCd);
        observation.setAltCdDescTxt(altCdDescTxt);
        observation.setAltCdSystemCd(altCdSystemCd);
        observation.setAltCdSystemDescTxt(altCdSystemDescTxt);
        observation.setCdDerivedInd(cdDerivedInd);
        observation.setRptToStateTime(rptToStateTime);
        observation.setCdVersion(cdVersion);
        observation.setProcessingDecisionCd(processingDecisionCd);
        observation.setPregnantIndCd(pregnantIndCd);
        observation.setPregnantWeek(pregnantWeek);
        observation.setProcessingDecisionTxt(processingDecisionTxt);

        // Assert
        assertEquals(observationUid, observation.getObservationUid());
        assertEquals(activityDurationAmt, observation.getActivityDurationAmt());
        assertEquals(activityDurationUnitCd, observation.getActivityDurationUnitCd());
        assertEquals(activityFromTime, observation.getActivityFromTime());
        assertEquals(activityToTime, observation.getActivityToTime());
        assertEquals(addReasonCd, observation.getAddReasonCd());
        assertEquals(addTime, observation.getAddTime());
        assertEquals(addUserId, observation.getAddUserId());
        assertEquals(cd, observation.getCd());
        assertEquals(cdDescTxt, observation.getCdDescTxt());
        assertEquals(cdSystemCd, observation.getCdSystemCd());
        assertEquals(cdSystemDescTxt, observation.getCdSystemDescTxt());
        assertEquals(confidentialityCd, observation.getConfidentialityCd());
        assertEquals(confidentialityDescTxt, observation.getConfidentialityDescTxt());
        assertEquals(ctrlCdDisplayForm, observation.getCtrlCdDisplayForm());
        assertEquals(ctrlCdUserDefined1, observation.getCtrlCdUserDefined1());
        assertEquals(ctrlCdUserDefined2, observation.getCtrlCdUserDefined2());
        assertEquals(ctrlCdUserDefined3, observation.getCtrlCdUserDefined3());
        assertEquals(ctrlCdUserDefined4, observation.getCtrlCdUserDefined4());
        assertEquals(derivationExp, observation.getDerivationExp());
        assertEquals(effectiveDurationAmt, observation.getEffectiveDurationAmt());
        assertEquals(effectiveDurationUnitCd, observation.getEffectiveDurationUnitCd());
        assertEquals(effectiveFromTime, observation.getEffectiveFromTime());
        assertEquals(effectiveToTime, observation.getEffectiveToTime());
        assertEquals(electronicInd, observation.getElectronicInd());
        assertEquals(groupLevelCd, observation.getGroupLevelCd());
        assertEquals(jurisdictionCd, observation.getJurisdictionCd());
        assertEquals(labConditionCd, observation.getLabConditionCd());
        assertEquals(lastChgReasonCd, observation.getLastChgReasonCd());
        assertEquals(lastChgTime, observation.getLastChgTime());
        assertEquals(lastChgUserId, observation.getLastChgUserId());
        assertEquals(localId, observation.getLocalId());
        assertEquals(methodCd, observation.getMethodCd());
        assertEquals(methodDescTxt, observation.getMethodDescTxt());
        assertEquals(obsDomainCd, observation.getObsDomainCd());
        assertEquals(obsDomainCdSt1, observation.getObsDomainCdSt1());
        assertEquals(pnuCd, observation.getPnuCd());
        assertEquals(priorityCd, observation.getPriorityCd());
        assertEquals(priorityDescTxt, observation.getPriorityDescTxt());
        assertEquals(progAreaCd, observation.getProgAreaCd());
        assertEquals(recordStatusCd, observation.getRecordStatusCd());
        assertEquals(recordStatusTime, observation.getRecordStatusTime());
        assertEquals(repeatNbr, observation.getRepeatNbr());
        assertEquals(statusCd, observation.getStatusCd());
        assertEquals(statusTime, observation.getStatusTime());
        assertEquals(subjectPersonUid, observation.getSubjectPersonUid());
        assertEquals(targetSiteCd, observation.getTargetSiteCd());
        assertEquals(targetSiteDescTxt, observation.getTargetSiteDescTxt());
        assertEquals(txt, observation.getTxt());
        assertEquals(userAffiliationTxt, observation.getUserAffiliationTxt());
        assertEquals(valueCd, observation.getValueCd());
        assertEquals(ynuCd, observation.getYnuCd());
        assertEquals(programJurisdictionOid, observation.getProgramJurisdictionOid());
        assertEquals(sharedInd, observation.getSharedInd());
        assertEquals(versionCtrlNbr, observation.getVersionCtrlNbr());
        assertEquals(altCd, observation.getAltCd());
        assertEquals(altCdDescTxt, observation.getAltCdDescTxt());
        assertEquals(altCdSystemCd, observation.getAltCdSystemCd());
        assertEquals(altCdSystemDescTxt, observation.getAltCdSystemDescTxt());
        assertEquals(cdDerivedInd, observation.getCdDerivedInd());
        assertEquals(rptToStateTime, observation.getRptToStateTime());
        assertEquals(cdVersion, observation.getCdVersion());
        assertEquals(processingDecisionCd, observation.getProcessingDecisionCd());
        assertEquals(pregnantIndCd, observation.getPregnantIndCd());
        assertEquals(pregnantWeek, observation.getPregnantWeek());
        assertEquals(processingDecisionTxt, observation.getProcessingDecisionTxt());
    }
}
