package gov.cdc.dataprocessing.constant.enums;

public enum LocalIdClass {
    COINFECTION_GROUP,
    EPILINK,
    GA,
    MATERIAL,
    NBS_DOCUMENT,
    NND_METADATA,
    NOTIFICATION,
    OBSERVATION,
    ORGANIZATION,
    PERSON,
    PUBLIC_HEALTH_CASE
}

/**
 UNUSED CODE
 //    GEOCODING,
 //    GEOCODING_LOG,
 //    GROUP,
 //    CS_REPORT,
 //    CT_CONTACT,
 //    CLINICAL_DOCUMENT,
 //    DEDUPLICATION_LOG,
 //    NBS_QUESTION_ID_LDF,
 //    NBS_QUESTION_LDF,
 //    NBS_UIMETEDATA_LDF,
 //    NON_LIVING_SUBJECT,
 //    INTERVENTION,
 //    PERSON_GROUP,
 //    PAGE,
 //    PATIENT_ENCOUNTER,
 //    PLACE,
 //    INTERVIEW,
 //    RDB_METADATA,
 //    REFERRAL,
 //    REPORT,
 //    REPORTDATASOURCE,
 //    REPORTDATASOURCECOLUMN,
 //    REPORTDISPLAYCOLUMN,
 //    REPORTFILTER,
 //    REPORTFILTERCODE,
 //    REPORTFILTERVALUE,
 //    SECURITY_LOG,
 //    TREATMENT,
 //    WORKUP

 *
 * */