package gov.cdc.dataprocessing.constant.enums;

public enum ObjectName {
    LOINC_CODES,
    RACE_CODES,
    PROGRAM_AREA_CODES,
    JURISDICTION_CODES,
    PROGRAM_AREA_CODES_WITH_NBS_UID,
    JURISDICTION_CODE_WITH_NBS_UID,
    ELR_XREF,
    CO_INFECTION_CONDITION_CODE,
    CONDITION_CODE,
    LAB_RESULT_DESC,
    SNOMED_CODE_BY_DESC,
    LAB_RESULT_DESC_WITH_ORGANISM_NAME,
    INVESTIGATION_FORM_CONDITION_CODE,
    LOIN_CODE_WITH_COMPONENT_NAME,
    CHECK_PAI_FOR_STD_OR_HIV,
    FIND_TO_CODE,
    GET_CODE_DESC_TXT_FOR_CD,
    GET_COUNTY_CD_BY_DESC,
    FIND_STATE_CODE_BY_STATE_NM,
    CODED_VALUE,
    GET_CODED_VALUES_CALL_REPOS,
    GET_CODED_VALUE,
    JURISDICTION_CODE_MAP_WITH_NBS_UID_KEY_SET

}
