apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  labels:
    service: kafka
spec:
  storageClassName: gp-kafka
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi