/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gov.cdc.dataingestion.hl7.parser;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        HL7ParserLibrary classUnderTest = new HL7ParserLibrary();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
