package gov.cdc.rticache.constant;

public enum ObjectName {
    LOINC_CODES,
    RACE_CODES,
    PROGRAM_AREA_CODES,
    JURISDICTION_CODES,
    PROGRAM_AREA_CODES_WITH_NBS_UID,
    JURISDICTION_CODE_WITH_NBS_UID,
    ELR_XREF,
    CO_INFECTION_CONDITION_CODE,
    CONDITION_CODE,
    LAB_RESULT_DESC,
    SNOMED_CODE_BY_DESC,
    LAB_RESULT_DESC_WITH_ORGANISM_NAME,
    INVESTIGATION_FORM_CONDITION_CODE,
    LOIN_CODE_WITH_COMPONENT_NAME,
    CHECK_PAI_FOR_STD_OR_HIV

}
