apiVersion: v1

kind: ConfigMap
metadata:
  name: phinadapter-config
data:
  odsedb_url: "jdbc:sqlserver://nbs-msgoute-20221213.cyyst6dg82wr.us-east-1.rds.amazonaws.com:1433;databaseName=nbs_odse_20211119"
  odsedb_username: "admin"
  odsedb_password: "7CQqXR3sCJuNfC8"
  jwt_enabled: "true"
  jwt_endpoint: "http://jwtgenerator:8000/jwt/v1/verify"
  jwt_seed: "monroe"
