apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: phinadapter
  name: phinadapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phinadapter
  template:
    metadata:
      labels:
        app: phinadapter
    spec:
      containers:
      - name: phinadapter
        imagePullPolicy: IfNotPresent
        image: phinadapter
        ports:
          - containerPort: 8090
        env:
          - name: HASHIVAULT_ENABLED
            value: "false"
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: phinadapter-config
                key: odsedb_url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: phinadapter-config
                key: odsedb_username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: phinadapter-config
                key: odsedb_password
          - name: JWT_ENABLED
            valueFrom:
              configMapKeyRef:
                name: phinadapter-config
                key: jwt_enabled
          - name: JWT_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: phinadapter-config
                key: jwt_endpoint
          - name: JWT_SEED
            valueFrom:
              configMapKeyRef:
                name: phinadapter-config
                key: jwt_seed

