version: '3.7'
services:
  nbsadapter:
    image: nbsadapter
    ports:
      - "8080:8080"
    networks:
      - apps_network
    volumes:
      - /tmp/hl7files:/tmp/hl7files

networks:
  apps_network:
      external:
        name: adapter_network



