/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gov.cdc.dataingestion.hl7.helper;

import ca.uhn.hl7v2.DefaultHapiContext;
import ca.uhn.hl7v2.HL7Exception;
import gov.cdc.dataingestion.hl7.helper.integration.DiHL7Exception;
import gov.cdc.dataingestion.hl7.helper.integration.HL7Parser;
import gov.cdc.dataingestion.hl7.helper.integration.interfaces.IHL7Parser;
import gov.cdc.dataingestion.hl7.helper.model.HL7ParsedMessage;

public class HL7ParserLibrary {

    private IHL7Parser parser = new HL7Parser(new DefaultHapiContext());

    public String hl7StringValidator(String message) throws DiHL7Exception {
        return parser.hl7MessageStringValidation(message);
    }

    public HL7ParsedMessage hl7StringParser(String message) throws DiHL7Exception {
        return parser.hl7StringParser(message);
    }
}
