server:
#  Designated PORT Is 8082
#  port: 8082
#  servlet:
#    context-path: /rti

info:
  app:
    name: RTI
    version: 1.0.0
    description: Real Time Ingestion

management:
  info:
    build:
      enabled: true
    java:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      roles: ADMIN
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info"
  prometheus:
    metrics:
      export:
        enabled: true

cache:
  clientId: ${RC_CLIENT_ID}
  secret: ${RC_CLIENT_SECRET}
  token: ${RC_URL}${RC_EP_TOKEN:/data/api/auth/token}
  srte:
    cacheString: ${RC_URL}${RC_EP_CACHE_STR:/data/srte/cache/string}
    cacheContain: ${RC_URL}${RC_EP_CACHE_CONTAIN:/data/srte/cache/contain}
    cacheObject: ${RC_URL}${RC_EP_CACHE_OBJ:/data/srte/cache/object}
  odse:
    localId: ${RC_URL}${EP_CACHE_LOCALID:/data/odse/localId}

features:
  modernizedMatching:
    enabled: ${MODERNIZED_MATCHING_ENABLED:false}
    url: ${MODERNIZED_MATCHING_URL}

spring:
  main:
    web-application-type: none
  application:
    name: data-processing-service
  cache:
    cache-names: srte
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=0

kafka:
  topic:
    elr_micro_transaction: elr_unprocessed_transaction
    elr_micro: dp_elr_unprocessed
    elr_health_case: dp_elr_processing_public_health_case
    elr_handle_lab: dp_elr_processing_handle_lab
    elr_edx_log: dp_elr_edx_log
    elr_action_tracker: dp_elr_action_tracker
nbs:
  user: ${NBS_AUTH_USER:superuser}
  data:
    hiv_program_areas: ${HIV_PROG_AREA:}

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:80}               # Increase for higher parallelism (adjust per CPU & DB limits)
      minimum-idle: ${HIKARI_MINIMUM_IDLE:0}                  # Let unused connections be removed
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:30000}              # Close idle connections quickly (30s)
      connection-timeout: ${HIKARI_CON_TIMEOUT:30000}         # Fail fast if no connection within 30s
      max-lifetime: ${HIKARI_MAX_LIFETIME:300000}             # Retire connections after 5 minutes (avoid stale connections)
      pool-name: ${HIKARI_POOL_NAME:SQLServerHikariCP}
      leak-detection-threshold: ${LEAK_DETECTION_THRESHOLD:20000}  # Log warnings if connection not returned in 20s (debug leaks)
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${NBS_DBUSER}
    password: ${NBS_DBPASSWORD}
    nbs:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=${NBS_MSGOUTE_DB_NAME:NBS_MSGOUTE};encrypt=true;trustServerCertificate=true;
    odse:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=${NBS_ODSE_DB_NAME:NBS_ODSE};encrypt=true;trustServerCertificate=true;
    srte:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=${NBS_SRTE_DB_NAME:NBS_SRTE};encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    thread: ${KAFKA_THREAD:1}
    max-poll-record: ${KAFKA_MAX_POLL_RECORD:10}
    group-id: data-processing-group-init
    group-id-phc: data-processing-group-phc
    group-id-lab: data-processing-group-lab
    group-id-edx: data-processing-group-edx
    consumer:
      maxPollIntervalMs: 30000
#K8S Profile goes here

service:
  timezone: ${SERVICE_TZ:UTC}

logging:
  level:
    root: WARN
    # Retain INFO logs for your own class
    gov.cdc.dataprocessing: INFO
    # Kafka internals
    org.apache.kafka: WARN
    # JPA / Hibernate
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    # HikariCP
    com.zaxxer.hikari: WARN
    # Spring Data JPA repositories
    org.springframework.data.jpa.repository: WARN
    # JDBC (optional)
    org.springframework.jdbc.core: WARN


feature:
  thread-enabled: ${THREAD_FLAG:true}
  jdbc-flag: ${JDBC_FLAG:true}
  thread-pool-size: ${THREAD_POOL_SIZE:5}
  thread-queue-size: ${THREAD_QUEUE_SIZE:1000}
