server:
  port: 8082
  servlet:
    context-path: /rti

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

cache:
  clientId: ${RC_CLIENT_ID:di-keycloak-client}
  secret: ${RC_CLIENT_SECRET:eVQ9n5zxyhUTHFmA2XhNfb6r8DYGlSI5}
  token: ${RC_URL}${RC_EP_TOKEN:http://localhost:8085/rti/api/auth/token}
  srte:
    cacheString: ${RC_URL}${RC_EP_CACHE_STR:http://localhost:8085/rti/srte/cache/string}
    cacheContain: ${RC_URL}${RC_EP_CACHE_CONTAIN:http://localhost:8085/rti/srte/cache/contain}
    cacheObject: ${RC_URL}${RC_EP_CACHE_OBJ:http://localhost:8085/rti/srte/cache/object}
  odse:
    localId: ${RC_URL}${EP_CACHE_LOCALID:http://localhost:8085/rti/odse/localId}

spring:
  application:
    name: data-processing-service
  cache:
    cache-names: srte
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=0

kafka:
  topic:
    elr_micro_transaction: elr_unprocessed_transaction
    elr_micro: elr_unprocessed
    elr_health_case: elr_processing_public_health_case
    elr_handle_lab: elr_processing_handle_lab
    elr_edx_log: elr_edx_log
    elr_action_tracker: elr_action_tracker

nbs:
  user:  ${NBS_AUTH_USER:superuser}
  data:
    hiv_program_areas: ${HIV_PROG_AREA:}

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${NBS_DBUSER}
    password: ${NBS_DBPASSWORD}
    nbs:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_MSGOUTE;encrypt=true;trustServerCertificate=true;
    odse:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;
    srte:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_SRTE;encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    group-id: data-processing-group
    consumer:
      maxPollIntervalMs: 30000

#K8S Profile goes here