//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ActionType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="CreateInvestigation" type="{http://www.cdc.gov/NEDSS}CreateInvestigationType"/>
 *         <element name="MarkAsReviewed" type="{http://www.cdc.gov/NEDSS}MarkAsReviewedType"/>
 *         <element name="CreateInvestigationWithNND" type="{http://www.cdc.gov/NEDSS}CreateInvestigationWithNNDType"/>
 *         <element name="DeleteDocument" type="{http://www.cdc.gov/NEDSS}DeleteDocumentType"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionType", propOrder = {
    "createInvestigation",
    "markAsReviewed",
    "createInvestigationWithNND",
    "deleteDocument"
})
public class ActionType {

    @XmlElement(name = "CreateInvestigation")
    protected CreateInvestigationType createInvestigation;
    @XmlElement(name = "MarkAsReviewed")
    protected MarkAsReviewedType markAsReviewed;
    @XmlElement(name = "CreateInvestigationWithNND")
    protected CreateInvestigationWithNNDType createInvestigationWithNND;
    @XmlElement(name = "DeleteDocument")
    protected DeleteDocumentType deleteDocument;

    /**
     * Gets the value of the createInvestigation property.
     * 
     * @return
     *     possible object is
     *     {@link CreateInvestigationType }
     *     
     */
    public CreateInvestigationType getCreateInvestigation() {
        return createInvestigation;
    }

    /**
     * Sets the value of the createInvestigation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateInvestigationType }
     *     
     */
    public void setCreateInvestigation(CreateInvestigationType value) {
        this.createInvestigation = value;
    }

    /**
     * Gets the value of the markAsReviewed property.
     * 
     * @return
     *     possible object is
     *     {@link MarkAsReviewedType }
     *     
     */
    public MarkAsReviewedType getMarkAsReviewed() {
        return markAsReviewed;
    }

    /**
     * Sets the value of the markAsReviewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkAsReviewedType }
     *     
     */
    public void setMarkAsReviewed(MarkAsReviewedType value) {
        this.markAsReviewed = value;
    }

    /**
     * Gets the value of the createInvestigationWithNND property.
     * 
     * @return
     *     possible object is
     *     {@link CreateInvestigationWithNNDType }
     *     
     */
    public CreateInvestigationWithNNDType getCreateInvestigationWithNND() {
        return createInvestigationWithNND;
    }

    /**
     * Sets the value of the createInvestigationWithNND property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateInvestigationWithNNDType }
     *     
     */
    public void setCreateInvestigationWithNND(CreateInvestigationWithNNDType value) {
        this.createInvestigationWithNND = value;
    }

    /**
     * Gets the value of the deleteDocument property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteDocumentType }
     *     
     */
    public DeleteDocumentType getDeleteDocument() {
        return deleteDocument;
    }

    /**
     * Sets the value of the deleteDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteDocumentType }
     *     
     */
    public void setDeleteDocument(DeleteDocumentType value) {
        this.deleteDocument = value;
    }

}
