//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for AlertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="AlertType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AlertSeverity" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="SendToRecipients" type="{http://www.cdc.gov/NEDSS}SendToRecipientsType" maxOccurs="unbounded"/>
 *         <element name="Comment" type="{http://www.cdc.gov/NEDSS}CommentsType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertType", propOrder = {
    "alertSeverity",
    "sendToRecipients",
    "comment"
})
public class AlertType {

    @XmlElement(name = "AlertSeverity", required = true)
    protected CodedType alertSeverity;
    @XmlElement(name = "SendToRecipients", required = true)
    protected List<SendToRecipientsType> sendToRecipients;
    @XmlElement(name = "Comment")
    protected String comment;

    /**
     * Gets the value of the alertSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getAlertSeverity() {
        return alertSeverity;
    }

    /**
     * Sets the value of the alertSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setAlertSeverity(CodedType value) {
        this.alertSeverity = value;
    }

    /**
     * Gets the value of the sendToRecipients property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the sendToRecipients property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSendToRecipients().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendToRecipientsType }
     * 
     * 
     * @return
     *     The value of the sendToRecipients property.
     */
    public List<SendToRecipientsType> getSendToRecipients() {
        if (sendToRecipients == null) {
            sendToRecipients = new ArrayList<>();
        }
        return this.sendToRecipients;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
