//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AlgorithmName">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <maxLength value="200"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Event" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="Frequency" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="AppliesToEntryMethods" type="{http://www.cdc.gov/NEDSS}EntryMethodType" minOccurs="0"/>
 *         <element name="InvestigationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ApplyToConditions" type="{http://www.cdc.gov/NEDSS}ApplyToConditionsType" minOccurs="0"/>
 *         <element name="ApplyToSendingSystems" type="{http://www.cdc.gov/NEDSS}SendingSystemType" minOccurs="0"/>
 *         <element name="ApplyToReportingFacilities" type="{http://www.cdc.gov/NEDSS}ReportingFacilityType" minOccurs="0"/>
 *         <element name="Comment" type="{http://www.cdc.gov/NEDSS}CommentsType" minOccurs="0"/>
 *         <element name="AdvancedCriteria" type="{http://www.cdc.gov/NEDSS}AdvancedCriteriaType" minOccurs="0"/>
 *         <element name="ElrAdvancedCriteria" type="{http://www.cdc.gov/NEDSS}ElrAdvancedCriteriaType" minOccurs="0"/>
 *         <element name="Action" type="{http://www.cdc.gov/NEDSS}ActionType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "algorithmName",
    "event",
    "frequency",
    "appliesToEntryMethods",
    "investigationType",
    "applyToConditions",
    "applyToSendingSystems",
    "applyToReportingFacilities",
    "comment",
    "advancedCriteria",
    "elrAdvancedCriteria",
    "action"
})
@XmlRootElement(name = "Algorithm")
public class Algorithm {

    @XmlElement(name = "AlgorithmName", required = true)
    protected String algorithmName;
    @XmlElement(name = "Event", required = true)
    protected CodedType event;
    @XmlElement(name = "Frequency", required = true)
    protected CodedType frequency;
    @XmlElement(name = "AppliesToEntryMethods")
    protected EntryMethodType appliesToEntryMethods;
    @XmlElement(name = "InvestigationType")
    protected String investigationType;
    @XmlElement(name = "ApplyToConditions")
    protected ApplyToConditionsType applyToConditions;
    @XmlElement(name = "ApplyToSendingSystems")
    protected SendingSystemType applyToSendingSystems;
    @XmlElement(name = "ApplyToReportingFacilities")
    protected ReportingFacilityType applyToReportingFacilities;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "AdvancedCriteria")
    protected AdvancedCriteriaType advancedCriteria;
    @XmlElement(name = "ElrAdvancedCriteria")
    protected ElrAdvancedCriteriaType elrAdvancedCriteria;
    @XmlElement(name = "Action", required = true)
    protected ActionType action;

    /**
     * Gets the value of the algorithmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgorithmName() {
        return algorithmName;
    }

    /**
     * Sets the value of the algorithmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgorithmName(String value) {
        this.algorithmName = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setEvent(CodedType value) {
        this.event = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setFrequency(CodedType value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the appliesToEntryMethods property.
     * 
     * @return
     *     possible object is
     *     {@link EntryMethodType }
     *     
     */
    public EntryMethodType getAppliesToEntryMethods() {
        return appliesToEntryMethods;
    }

    /**
     * Sets the value of the appliesToEntryMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryMethodType }
     *     
     */
    public void setAppliesToEntryMethods(EntryMethodType value) {
        this.appliesToEntryMethods = value;
    }

    /**
     * Gets the value of the investigationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestigationType() {
        return investigationType;
    }

    /**
     * Sets the value of the investigationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestigationType(String value) {
        this.investigationType = value;
    }

    /**
     * Gets the value of the applyToConditions property.
     * 
     * @return
     *     possible object is
     *     {@link ApplyToConditionsType }
     *     
     */
    public ApplyToConditionsType getApplyToConditions() {
        return applyToConditions;
    }

    /**
     * Sets the value of the applyToConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplyToConditionsType }
     *     
     */
    public void setApplyToConditions(ApplyToConditionsType value) {
        this.applyToConditions = value;
    }

    /**
     * Gets the value of the applyToSendingSystems property.
     * 
     * @return
     *     possible object is
     *     {@link SendingSystemType }
     *     
     */
    public SendingSystemType getApplyToSendingSystems() {
        return applyToSendingSystems;
    }

    /**
     * Sets the value of the applyToSendingSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendingSystemType }
     *     
     */
    public void setApplyToSendingSystems(SendingSystemType value) {
        this.applyToSendingSystems = value;
    }

    /**
     * Gets the value of the applyToReportingFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingFacilityType }
     *     
     */
    public ReportingFacilityType getApplyToReportingFacilities() {
        return applyToReportingFacilities;
    }

    /**
     * Sets the value of the applyToReportingFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingFacilityType }
     *     
     */
    public void setApplyToReportingFacilities(ReportingFacilityType value) {
        this.applyToReportingFacilities = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the advancedCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link AdvancedCriteriaType }
     *     
     */
    public AdvancedCriteriaType getAdvancedCriteria() {
        return advancedCriteria;
    }

    /**
     * Sets the value of the advancedCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvancedCriteriaType }
     *     
     */
    public void setAdvancedCriteria(AdvancedCriteriaType value) {
        this.advancedCriteria = value;
    }

    /**
     * Gets the value of the elrAdvancedCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link ElrAdvancedCriteriaType }
     *     
     */
    public ElrAdvancedCriteriaType getElrAdvancedCriteria() {
        return elrAdvancedCriteria;
    }

    /**
     * Sets the value of the elrAdvancedCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElrAdvancedCriteriaType }
     *     
     */
    public void setElrAdvancedCriteria(ElrAdvancedCriteriaType value) {
        this.elrAdvancedCriteria = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

}
