//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for CodedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CodedType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Code" type="{http://www.cdc.gov/NEDSS}CodeType" minOccurs="0"/>
 *         <element name="CodeDescTxt" type="{http://www.cdc.gov/NEDSS}CodeDescTxtType" minOccurs="0"/>
 *         <element name="CodeSystemCode" type="{http://www.cdc.gov/NEDSS}CodeSystemCodeType" minOccurs="0"/>
 *         <element name="AlternateCode" type="{http://www.cdc.gov/NEDSS}CodeType" minOccurs="0"/>
 *         <element name="AlternateCodeDescTxt" type="{http://www.cdc.gov/NEDSS}CodeDescTxtType" minOccurs="0"/>
 *         <element name="AlternateCodeSystemCode" type="{http://www.cdc.gov/NEDSS}CodeSystemCodeType" minOccurs="0"/>
 *         <element name="CodeSystemVersionID" type="{http://www.cdc.gov/NEDSS}CodeSystemVersionIDType" minOccurs="0"/>
 *         <element name="AlternateCodeSystemVersionID" type="{http://www.cdc.gov/NEDSS}CodeSystemVersionIDType" minOccurs="0"/>
 *         <element name="Text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodedType", propOrder = {
    "code",
    "codeDescTxt",
    "codeSystemCode",
    "alternateCode",
    "alternateCodeDescTxt",
    "alternateCodeSystemCode",
    "codeSystemVersionID",
    "alternateCodeSystemVersionID",
    "text"
})
public class CodedType {

    @XmlElement(name = "Code")
    protected String code;
    @XmlElement(name = "CodeDescTxt")
    protected String codeDescTxt;
    @XmlElementRef(name = "CodeSystemCode", namespace = "http://www.cdc.gov/NEDSS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> codeSystemCode;
    @XmlElement(name = "AlternateCode")
    protected String alternateCode;
    @XmlElement(name = "AlternateCodeDescTxt")
    protected String alternateCodeDescTxt;
    @XmlElement(name = "AlternateCodeSystemCode")
    protected String alternateCodeSystemCode;
    @XmlElement(name = "CodeSystemVersionID")
    protected String codeSystemVersionID;
    @XmlElement(name = "AlternateCodeSystemVersionID")
    protected String alternateCodeSystemVersionID;
    @XmlElement(name = "Text")
    protected String text;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeDescTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeDescTxt() {
        return codeDescTxt;
    }

    /**
     * Sets the value of the codeDescTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeDescTxt(String value) {
        this.codeDescTxt = value;
    }

    /**
     * Gets the value of the codeSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodeSystemCode() {
        return codeSystemCode;
    }

    /**
     * Sets the value of the codeSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodeSystemCode(JAXBElement<String> value) {
        this.codeSystemCode = value;
    }

    /**
     * Gets the value of the alternateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCode() {
        return alternateCode;
    }

    /**
     * Sets the value of the alternateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCode(String value) {
        this.alternateCode = value;
    }

    /**
     * Gets the value of the alternateCodeDescTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCodeDescTxt() {
        return alternateCodeDescTxt;
    }

    /**
     * Sets the value of the alternateCodeDescTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCodeDescTxt(String value) {
        this.alternateCodeDescTxt = value;
    }

    /**
     * Gets the value of the alternateCodeSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCodeSystemCode() {
        return alternateCodeSystemCode;
    }

    /**
     * Sets the value of the alternateCodeSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCodeSystemCode(String value) {
        this.alternateCodeSystemCode = value;
    }

    /**
     * Gets the value of the codeSystemVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSystemVersionID() {
        return codeSystemVersionID;
    }

    /**
     * Sets the value of the codeSystemVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSystemVersionID(String value) {
        this.codeSystemVersionID = value;
    }

    /**
     * Gets the value of the alternateCodeSystemVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCodeSystemVersionID() {
        return alternateCodeSystemVersionID;
    }

    /**
     * Sets the value of the alternateCodeSystemVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCodeSystemVersionID(String value) {
        this.alternateCodeSystemVersionID = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
