//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateInvestigationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CreateInvestigationType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="UpdateAction" type="{http://www.cdc.gov/NEDSS}CodedType" minOccurs="0"/>
 *         <element name="OnFailureToCreateInvestigation" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="Alert" type="{http://www.cdc.gov/NEDSS}AlertType" minOccurs="0"/>
 *         <element name="InvestigationDefaultValues" type="{http://www.cdc.gov/NEDSS}InvestigationDefaultValuesType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateInvestigationType", propOrder = {
    "updateAction",
    "onFailureToCreateInvestigation",
    "alert",
    "investigationDefaultValues"
})
public class CreateInvestigationType {

    @XmlElement(name = "UpdateAction")
    protected CodedType updateAction;
    @XmlElement(name = "OnFailureToCreateInvestigation", required = true)
    protected CodedType onFailureToCreateInvestigation;
    @XmlElement(name = "Alert")
    protected AlertType alert;
    @XmlElement(name = "InvestigationDefaultValues")
    protected InvestigationDefaultValuesType investigationDefaultValues;

    /**
     * Gets the value of the updateAction property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getUpdateAction() {
        return updateAction;
    }

    /**
     * Sets the value of the updateAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setUpdateAction(CodedType value) {
        this.updateAction = value;
    }

    /**
     * Gets the value of the onFailureToCreateInvestigation property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getOnFailureToCreateInvestigation() {
        return onFailureToCreateInvestigation;
    }

    /**
     * Sets the value of the onFailureToCreateInvestigation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setOnFailureToCreateInvestigation(CodedType value) {
        this.onFailureToCreateInvestigation = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * @return
     *     possible object is
     *     {@link AlertType }
     *     
     */
    public AlertType getAlert() {
        return alert;
    }

    /**
     * Sets the value of the alert property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertType }
     *     
     */
    public void setAlert(AlertType value) {
        this.alert = value;
    }

    /**
     * Gets the value of the investigationDefaultValues property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigationDefaultValuesType }
     *     
     */
    public InvestigationDefaultValuesType getInvestigationDefaultValues() {
        return investigationDefaultValues;
    }

    /**
     * Sets the value of the investigationDefaultValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigationDefaultValuesType }
     *     
     */
    public void setInvestigationDefaultValues(InvestigationDefaultValuesType value) {
        this.investigationDefaultValues = value;
    }

}
