//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CriteriaType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CriteriaQuestion" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="CriteriaLogic" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <choice>
 *           <element name="CriteriaStringValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           <element name="CriteriaNumericValue" type="{http://www.cdc.gov/NEDSS}NumericType"/>
 *           <element name="CriteriaCodedValue" type="{http://www.cdc.gov/NEDSS}CodedType" maxOccurs="unbounded"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CriteriaType", propOrder = {
    "criteriaQuestion",
    "criteriaLogic",
    "criteriaStringValue",
    "criteriaNumericValue",
    "criteriaCodedValue"
})
public class CriteriaType {

    @XmlElement(name = "CriteriaQuestion", required = true)
    protected CodedType criteriaQuestion;
    @XmlElement(name = "CriteriaLogic", required = true)
    protected CodedType criteriaLogic;
    @XmlElement(name = "CriteriaStringValue")
    protected String criteriaStringValue;
    @XmlElement(name = "CriteriaNumericValue")
    protected NumericType criteriaNumericValue;
    @XmlElement(name = "CriteriaCodedValue")
    protected List<CodedType> criteriaCodedValue;

    /**
     * Gets the value of the criteriaQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getCriteriaQuestion() {
        return criteriaQuestion;
    }

    /**
     * Sets the value of the criteriaQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setCriteriaQuestion(CodedType value) {
        this.criteriaQuestion = value;
    }

    /**
     * Gets the value of the criteriaLogic property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getCriteriaLogic() {
        return criteriaLogic;
    }

    /**
     * Sets the value of the criteriaLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setCriteriaLogic(CodedType value) {
        this.criteriaLogic = value;
    }

    /**
     * Gets the value of the criteriaStringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCriteriaStringValue() {
        return criteriaStringValue;
    }

    /**
     * Sets the value of the criteriaStringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCriteriaStringValue(String value) {
        this.criteriaStringValue = value;
    }

    /**
     * Gets the value of the criteriaNumericValue property.
     * 
     * @return
     *     possible object is
     *     {@link NumericType }
     *     
     */
    public NumericType getCriteriaNumericValue() {
        return criteriaNumericValue;
    }

    /**
     * Sets the value of the criteriaNumericValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericType }
     *     
     */
    public void setCriteriaNumericValue(NumericType value) {
        this.criteriaNumericValue = value;
    }

    /**
     * Gets the value of the criteriaCodedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the criteriaCodedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCriteriaCodedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedType }
     * 
     * 
     * @return
     *     The value of the criteriaCodedValue property.
     */
    public List<CodedType> getCriteriaCodedValue() {
        if (criteriaCodedValue == null) {
            criteriaCodedValue = new ArrayList<>();
        }
        return this.criteriaCodedValue;
    }

}
