//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DefaultValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DefaultValueType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DefaultQuestion" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="DefaultBehavior" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <choice>
 *           <element name="DefaultStringValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           <element name="DefaultCommentValue" type="{http://www.cdc.gov/NEDSS}CommentsType"/>
 *           <element name="DefaultNumericValue" type="{http://www.cdc.gov/NEDSS}NumericType"/>
 *           <element name="DefaultCodedValue" type="{http://www.cdc.gov/NEDSS}CodedType" maxOccurs="unbounded"/>
 *           <element name="DefaultParticipation" type="{http://www.cdc.gov/NEDSS}DefaultParticipationType"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefaultValueType", propOrder = {
    "defaultQuestion",
    "defaultBehavior",
    "defaultStringValue",
    "defaultCommentValue",
    "defaultNumericValue",
    "defaultCodedValue",
    "defaultParticipation"
})
public class DefaultValueType {

    @XmlElement(name = "DefaultQuestion", required = true)
    protected CodedType defaultQuestion;
    @XmlElement(name = "DefaultBehavior", required = true)
    protected CodedType defaultBehavior;
    @XmlElement(name = "DefaultStringValue")
    protected String defaultStringValue;
    @XmlElement(name = "DefaultCommentValue")
    protected String defaultCommentValue;
    @XmlElement(name = "DefaultNumericValue")
    protected NumericType defaultNumericValue;
    @XmlElement(name = "DefaultCodedValue")
    protected List<CodedType> defaultCodedValue;
    @XmlElement(name = "DefaultParticipation")
    protected DefaultParticipationType defaultParticipation;

    /**
     * Gets the value of the defaultQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getDefaultQuestion() {
        return defaultQuestion;
    }

    /**
     * Sets the value of the defaultQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setDefaultQuestion(CodedType value) {
        this.defaultQuestion = value;
    }

    /**
     * Gets the value of the defaultBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getDefaultBehavior() {
        return defaultBehavior;
    }

    /**
     * Sets the value of the defaultBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setDefaultBehavior(CodedType value) {
        this.defaultBehavior = value;
    }

    /**
     * Gets the value of the defaultStringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultStringValue() {
        return defaultStringValue;
    }

    /**
     * Sets the value of the defaultStringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultStringValue(String value) {
        this.defaultStringValue = value;
    }

    /**
     * Gets the value of the defaultCommentValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCommentValue() {
        return defaultCommentValue;
    }

    /**
     * Sets the value of the defaultCommentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCommentValue(String value) {
        this.defaultCommentValue = value;
    }

    /**
     * Gets the value of the defaultNumericValue property.
     * 
     * @return
     *     possible object is
     *     {@link NumericType }
     *     
     */
    public NumericType getDefaultNumericValue() {
        return defaultNumericValue;
    }

    /**
     * Sets the value of the defaultNumericValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericType }
     *     
     */
    public void setDefaultNumericValue(NumericType value) {
        this.defaultNumericValue = value;
    }

    /**
     * Gets the value of the defaultCodedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the defaultCodedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultCodedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedType }
     * 
     * 
     * @return
     *     The value of the defaultCodedValue property.
     */
    public List<CodedType> getDefaultCodedValue() {
        if (defaultCodedValue == null) {
            defaultCodedValue = new ArrayList<>();
        }
        return this.defaultCodedValue;
    }

    /**
     * Gets the value of the defaultParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultParticipationType }
     *     
     */
    public DefaultParticipationType getDefaultParticipation() {
        return defaultParticipation;
    }

    /**
     * Sets the value of the defaultParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultParticipationType }
     *     
     */
    public void setDefaultParticipation(DefaultParticipationType value) {
        this.defaultParticipation = value;
    }

}
