//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeleteDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DeleteDocumentType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ReasonForDeletion" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="Comment" type="{http://www.cdc.gov/NEDSS}CommentsType" minOccurs="0"/>
 *         <element name="Alert" type="{http://www.cdc.gov/NEDSS}AlertType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeleteDocumentType", propOrder = {
    "reasonForDeletion",
    "comment",
    "alert"
})
public class DeleteDocumentType {

    @XmlElement(name = "ReasonForDeletion", required = true)
    protected CodedType reasonForDeletion;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "Alert")
    protected AlertType alert;

    /**
     * Gets the value of the reasonForDeletion property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getReasonForDeletion() {
        return reasonForDeletion;
    }

    /**
     * Sets the value of the reasonForDeletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setReasonForDeletion(CodedType value) {
        this.reasonForDeletion = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * @return
     *     possible object is
     *     {@link AlertType }
     *     
     */
    public AlertType getAlert() {
        return alert;
    }

    /**
     * Sets the value of the alert property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertType }
     *     
     */
    public void setAlert(AlertType value) {
        this.alert = value;
    }

}
