//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ElrAdvancedCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ElrAdvancedCriteriaType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="EventDateLogic" type="{http://www.cdc.gov/NEDSS}EventDateLogicType" minOccurs="0"/>
 *         <element name="AndOrLogic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ElrCriteria" type="{http://www.cdc.gov/NEDSS}ElrCriteriaType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="InvCriteria" type="{http://www.cdc.gov/NEDSS}InvCriteriaType" minOccurs="0"/>
 *         <element name="InvLogic" type="{http://www.cdc.gov/NEDSS}InvLogicType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElrAdvancedCriteriaType", propOrder = {
    "eventDateLogic",
    "andOrLogic",
    "elrCriteria",
    "invCriteria",
    "invLogic"
})
public class ElrAdvancedCriteriaType {

    @XmlElement(name = "EventDateLogic")
    protected EventDateLogicType eventDateLogic;
    @XmlElement(name = "AndOrLogic", defaultValue = "AND")
    protected String andOrLogic;
    @XmlElement(name = "ElrCriteria")
    protected List<ElrCriteriaType> elrCriteria;
    @XmlElement(name = "InvCriteria")
    protected InvCriteriaType invCriteria;
    @XmlElement(name = "InvLogic")
    protected InvLogicType invLogic;

    /**
     * Gets the value of the eventDateLogic property.
     * 
     * @return
     *     possible object is
     *     {@link EventDateLogicType }
     *     
     */
    public EventDateLogicType getEventDateLogic() {
        return eventDateLogic;
    }

    /**
     * Sets the value of the eventDateLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDateLogicType }
     *     
     */
    public void setEventDateLogic(EventDateLogicType value) {
        this.eventDateLogic = value;
    }

    /**
     * Gets the value of the andOrLogic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAndOrLogic() {
        return andOrLogic;
    }

    /**
     * Sets the value of the andOrLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAndOrLogic(String value) {
        this.andOrLogic = value;
    }

    /**
     * Gets the value of the elrCriteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the elrCriteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElrCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElrCriteriaType }
     * 
     * 
     * @return
     *     The value of the elrCriteria property.
     */
    public List<ElrCriteriaType> getElrCriteria() {
        if (elrCriteria == null) {
            elrCriteria = new ArrayList<>();
        }
        return this.elrCriteria;
    }

    /**
     * Gets the value of the invCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link InvCriteriaType }
     *     
     */
    public InvCriteriaType getInvCriteria() {
        return invCriteria;
    }

    /**
     * Sets the value of the invCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvCriteriaType }
     *     
     */
    public void setInvCriteria(InvCriteriaType value) {
        this.invCriteria = value;
    }

    /**
     * Gets the value of the invLogic property.
     * 
     * @return
     *     possible object is
     *     {@link InvLogicType }
     *     
     */
    public InvLogicType getInvLogic() {
        return invLogic;
    }

    /**
     * Sets the value of the invLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvLogicType }
     *     
     */
    public void setInvLogic(InvLogicType value) {
        this.invLogic = value;
    }

}
