//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElrCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ElrCriteriaType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ResultedTest" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <choice>
 *           <element name="ElrCodedResultValue" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *           <element name="ElrTextResultValue" type="{http://www.cdc.gov/NEDSS}TextType"/>
 *           <element name="ElrNumericResultValue" type="{http://www.cdc.gov/NEDSS}ElrNumericType"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElrCriteriaType", propOrder = {
    "resultedTest",
    "elrCodedResultValue",
    "elrTextResultValue",
    "elrNumericResultValue"
})
public class ElrCriteriaType {

    @XmlElement(name = "ResultedTest", required = true)
    protected CodedType resultedTest;
    @XmlElement(name = "ElrCodedResultValue")
    protected CodedType elrCodedResultValue;
    @XmlElement(name = "ElrTextResultValue")
    protected TextType elrTextResultValue;
    @XmlElement(name = "ElrNumericResultValue")
    protected ElrNumericType elrNumericResultValue;

    /**
     * Gets the value of the resultedTest property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getResultedTest() {
        return resultedTest;
    }

    /**
     * Sets the value of the resultedTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setResultedTest(CodedType value) {
        this.resultedTest = value;
    }

    /**
     * Gets the value of the elrCodedResultValue property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getElrCodedResultValue() {
        return elrCodedResultValue;
    }

    /**
     * Sets the value of the elrCodedResultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setElrCodedResultValue(CodedType value) {
        this.elrCodedResultValue = value;
    }

    /**
     * Gets the value of the elrTextResultValue property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getElrTextResultValue() {
        return elrTextResultValue;
    }

    /**
     * Sets the value of the elrTextResultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setElrTextResultValue(TextType value) {
        this.elrTextResultValue = value;
    }

    /**
     * Gets the value of the elrNumericResultValue property.
     * 
     * @return
     *     possible object is
     *     {@link ElrNumericType }
     *     
     */
    public ElrNumericType getElrNumericResultValue() {
        return elrNumericResultValue;
    }

    /**
     * Sets the value of the elrNumericResultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElrNumericType }
     *     
     */
    public void setElrNumericResultValue(ElrNumericType value) {
        this.elrNumericResultValue = value;
    }

}
