//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventDateLogicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="EventDateLogicType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ElrTimeLogic" type="{http://www.cdc.gov/NEDSS}ElrTimeLogicType" minOccurs="0"/>
 *         <element name="ElrSourceElement" type="{http://www.cdc.gov/NEDSS}CodedType" minOccurs="0"/>
 *         <element name="WithinTimePeriod" type="{http://www.cdc.gov/NEDSS}IntegerNumericType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventDateLogicType", propOrder = {
    "elrTimeLogic",
    "elrSourceElement",
    "withinTimePeriod"
})
public class EventDateLogicType {

    @XmlElement(name = "ElrTimeLogic")
    protected ElrTimeLogicType elrTimeLogic;
    @XmlElement(name = "ElrSourceElement")
    protected CodedType elrSourceElement;
    @XmlElement(name = "WithinTimePeriod")
    protected IntegerNumericType withinTimePeriod;

    /**
     * Gets the value of the elrTimeLogic property.
     * 
     * @return
     *     possible object is
     *     {@link ElrTimeLogicType }
     *     
     */
    public ElrTimeLogicType getElrTimeLogic() {
        return elrTimeLogic;
    }

    /**
     * Sets the value of the elrTimeLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElrTimeLogicType }
     *     
     */
    public void setElrTimeLogic(ElrTimeLogicType value) {
        this.elrTimeLogic = value;
    }

    /**
     * Gets the value of the elrSourceElement property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getElrSourceElement() {
        return elrSourceElement;
    }

    /**
     * Sets the value of the elrSourceElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setElrSourceElement(CodedType value) {
        this.elrSourceElement = value;
    }

    /**
     * Gets the value of the withinTimePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerNumericType }
     *     
     */
    public IntegerNumericType getWithinTimePeriod() {
        return withinTimePeriod;
    }

    /**
     * Sets the value of the withinTimePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerNumericType }
     *     
     */
    public void setWithinTimePeriod(IntegerNumericType value) {
        this.withinTimePeriod = value;
    }

}
