//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvParticipationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="InvParticipationType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ParticipationType" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="EntityClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="EntityUid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvParticipationType", propOrder = {
    "participationType",
    "entityClass",
    "entityUid"
})
public class InvParticipationType {

    @XmlElement(name = "ParticipationType", required = true)
    protected CodedType participationType;
    @XmlElement(name = "EntityClass")
    protected String entityClass;
    @XmlElement(name = "EntityUid")
    protected String entityUid;

    /**
     * Gets the value of the participationType property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getParticipationType() {
        return participationType;
    }

    /**
     * Sets the value of the participationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setParticipationType(CodedType value) {
        this.participationType = value;
    }

    /**
     * Gets the value of the entityClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityClass() {
        return entityClass;
    }

    /**
     * Sets the value of the entityClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityClass(String value) {
        this.entityClass = value;
    }

    /**
     * Gets the value of the entityUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityUid() {
        return entityUid;
    }

    /**
     * Sets the value of the entityUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityUid(String value) {
        this.entityUid = value;
    }

}
