//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for InvValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="InvValueType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="InvQuestion" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="InvQuestionLogic" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <choice>
 *           <element name="InvStringValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           <element name="InvCommentValue" type="{http://www.cdc.gov/NEDSS}CommentsType"/>
 *           <element name="InvNumericValue" type="{http://www.cdc.gov/NEDSS}NumericType"/>
 *           <element name="InvCodedValue" type="{http://www.cdc.gov/NEDSS}CodedType" maxOccurs="unbounded"/>
 *           <element name="InvParticipation" type="{http://www.cdc.gov/NEDSS}InvParticipationType"/>
 *         </choice>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvValueType", propOrder = {
    "invQuestion",
    "invQuestionLogic",
    "invStringValue",
    "invCommentValue",
    "invNumericValue",
    "invCodedValue",
    "invParticipation"
})
public class InvValueType {

    @XmlElement(name = "InvQuestion", required = true)
    protected CodedType invQuestion;
    @XmlElement(name = "InvQuestionLogic", required = true)
    protected CodedType invQuestionLogic;
    @XmlElement(name = "InvStringValue")
    protected String invStringValue;
    @XmlElement(name = "InvCommentValue")
    protected String invCommentValue;
    @XmlElement(name = "InvNumericValue")
    protected NumericType invNumericValue;
    @XmlElement(name = "InvCodedValue")
    protected List<CodedType> invCodedValue;
    @XmlElement(name = "InvParticipation")
    protected InvParticipationType invParticipation;

    /**
     * Gets the value of the invQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getInvQuestion() {
        return invQuestion;
    }

    /**
     * Sets the value of the invQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setInvQuestion(CodedType value) {
        this.invQuestion = value;
    }

    /**
     * Gets the value of the invQuestionLogic property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getInvQuestionLogic() {
        return invQuestionLogic;
    }

    /**
     * Sets the value of the invQuestionLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setInvQuestionLogic(CodedType value) {
        this.invQuestionLogic = value;
    }

    /**
     * Gets the value of the invStringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvStringValue() {
        return invStringValue;
    }

    /**
     * Sets the value of the invStringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvStringValue(String value) {
        this.invStringValue = value;
    }

    /**
     * Gets the value of the invCommentValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvCommentValue() {
        return invCommentValue;
    }

    /**
     * Sets the value of the invCommentValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvCommentValue(String value) {
        this.invCommentValue = value;
    }

    /**
     * Gets the value of the invNumericValue property.
     * 
     * @return
     *     possible object is
     *     {@link NumericType }
     *     
     */
    public NumericType getInvNumericValue() {
        return invNumericValue;
    }

    /**
     * Sets the value of the invNumericValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericType }
     *     
     */
    public void setInvNumericValue(NumericType value) {
        this.invNumericValue = value;
    }

    /**
     * Gets the value of the invCodedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the invCodedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInvCodedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodedType }
     * 
     * 
     * @return
     *     The value of the invCodedValue property.
     */
    public List<CodedType> getInvCodedValue() {
        if (invCodedValue == null) {
            invCodedValue = new ArrayList<>();
        }
        return this.invCodedValue;
    }

    /**
     * Gets the value of the invParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link InvParticipationType }
     *     
     */
    public InvParticipationType getInvParticipation() {
        return invParticipation;
    }

    /**
     * Sets the value of the invParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvParticipationType }
     *     
     */
    public void setInvParticipation(InvParticipationType value) {
        this.invParticipation = value;
    }

}
