//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarkAsReviewedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MarkAsReviewedType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OnFailureToMarkAsReviewed" type="{http://www.cdc.gov/NEDSS}CodedType"/>
 *         <element name="NoActionReason" type="{http://www.cdc.gov/NEDSS}CodedType" minOccurs="0"/>
 *         <element name="AdditionalComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkAsReviewedType", propOrder = {
    "onFailureToMarkAsReviewed",
    "noActionReason",
    "additionalComment"
})
public class MarkAsReviewedType {

    @XmlElement(name = "OnFailureToMarkAsReviewed", required = true)
    protected CodedType onFailureToMarkAsReviewed;
    @XmlElement(name = "NoActionReason")
    protected CodedType noActionReason;
    @XmlElement(name = "AdditionalComment")
    protected String additionalComment;

    /**
     * Gets the value of the onFailureToMarkAsReviewed property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getOnFailureToMarkAsReviewed() {
        return onFailureToMarkAsReviewed;
    }

    /**
     * Sets the value of the onFailureToMarkAsReviewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setOnFailureToMarkAsReviewed(CodedType value) {
        this.onFailureToMarkAsReviewed = value;
    }

    /**
     * Gets the value of the noActionReason property.
     * 
     * @return
     *     possible object is
     *     {@link CodedType }
     *     
     */
    public CodedType getNoActionReason() {
        return noActionReason;
    }

    /**
     * Sets the value of the noActionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodedType }
     *     
     */
    public void setNoActionReason(CodedType value) {
        this.noActionReason = value;
    }

    /**
     * Gets the value of the additionalComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalComment() {
        return additionalComment;
    }

    /**
     * Sets the value of the additionalComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalComment(String value) {
        this.additionalComment = value;
    }

}
