//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.cdc.nbsDedup.model.dsma_algorithm;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.cdc.dataprocessing.model.dsma_algorithm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CodedTypeCodeSystemCode_QNAME = new QName("http://www.cdc.gov/NEDSS", "CodeSystemCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.cdc.dataprocessing.model.dsma_algorithm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Algorithm }
     * 
     * @return
     *     the new instance of {@link Algorithm }
     */
    public Algorithm createAlgorithm() {
        return new Algorithm();
    }

    /**
     * Create an instance of {@link CodedType }
     * 
     * @return
     *     the new instance of {@link CodedType }
     */
    public CodedType createCodedType() {
        return new CodedType();
    }

    /**
     * Create an instance of {@link EntryMethodType }
     * 
     * @return
     *     the new instance of {@link EntryMethodType }
     */
    public EntryMethodType createEntryMethodType() {
        return new EntryMethodType();
    }

    /**
     * Create an instance of {@link ApplyToConditionsType }
     * 
     * @return
     *     the new instance of {@link ApplyToConditionsType }
     */
    public ApplyToConditionsType createApplyToConditionsType() {
        return new ApplyToConditionsType();
    }

    /**
     * Create an instance of {@link SendingSystemType }
     * 
     * @return
     *     the new instance of {@link SendingSystemType }
     */
    public SendingSystemType createSendingSystemType() {
        return new SendingSystemType();
    }

    /**
     * Create an instance of {@link ReportingFacilityType }
     * 
     * @return
     *     the new instance of {@link ReportingFacilityType }
     */
    public ReportingFacilityType createReportingFacilityType() {
        return new ReportingFacilityType();
    }

    /**
     * Create an instance of {@link AdvancedCriteriaType }
     * 
     * @return
     *     the new instance of {@link AdvancedCriteriaType }
     */
    public AdvancedCriteriaType createAdvancedCriteriaType() {
        return new AdvancedCriteriaType();
    }

    /**
     * Create an instance of {@link ElrAdvancedCriteriaType }
     * 
     * @return
     *     the new instance of {@link ElrAdvancedCriteriaType }
     */
    public ElrAdvancedCriteriaType createElrAdvancedCriteriaType() {
        return new ElrAdvancedCriteriaType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     * @return
     *     the new instance of {@link ActionType }
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link AlertType }
     * 
     * @return
     *     the new instance of {@link AlertType }
     */
    public AlertType createAlertType() {
        return new AlertType();
    }

    /**
     * Create an instance of {@link CreateInvestigationType }
     * 
     * @return
     *     the new instance of {@link CreateInvestigationType }
     */
    public CreateInvestigationType createCreateInvestigationType() {
        return new CreateInvestigationType();
    }

    /**
     * Create an instance of {@link MarkAsReviewedType }
     * 
     * @return
     *     the new instance of {@link MarkAsReviewedType }
     */
    public MarkAsReviewedType createMarkAsReviewedType() {
        return new MarkAsReviewedType();
    }

    /**
     * Create an instance of {@link CreateInvestigationWithNNDType }
     * 
     * @return
     *     the new instance of {@link CreateInvestigationWithNNDType }
     */
    public CreateInvestigationWithNNDType createCreateInvestigationWithNNDType() {
        return new CreateInvestigationWithNNDType();
    }

    /**
     * Create an instance of {@link CriteriaType }
     * 
     * @return
     *     the new instance of {@link CriteriaType }
     */
    public CriteriaType createCriteriaType() {
        return new CriteriaType();
    }

    /**
     * Create an instance of {@link ElrCriteriaType }
     * 
     * @return
     *     the new instance of {@link ElrCriteriaType }
     */
    public ElrCriteriaType createElrCriteriaType() {
        return new ElrCriteriaType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     * @return
     *     the new instance of {@link TextType }
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link DeleteDocumentType }
     * 
     * @return
     *     the new instance of {@link DeleteDocumentType }
     */
    public DeleteDocumentType createDeleteDocumentType() {
        return new DeleteDocumentType();
    }

    /**
     * Create an instance of {@link InvestigationDefaultValuesType }
     * 
     * @return
     *     the new instance of {@link InvestigationDefaultValuesType }
     */
    public InvestigationDefaultValuesType createInvestigationDefaultValuesType() {
        return new InvestigationDefaultValuesType();
    }

    /**
     * Create an instance of {@link DefaultParticipationType }
     * 
     * @return
     *     the new instance of {@link DefaultParticipationType }
     */
    public DefaultParticipationType createDefaultParticipationType() {
        return new DefaultParticipationType();
    }

    /**
     * Create an instance of {@link DefaultValueType }
     * 
     * @return
     *     the new instance of {@link DefaultValueType }
     */
    public DefaultValueType createDefaultValueType() {
        return new DefaultValueType();
    }

    /**
     * Create an instance of {@link InvCriteriaType }
     * 
     * @return
     *     the new instance of {@link InvCriteriaType }
     */
    public InvCriteriaType createInvCriteriaType() {
        return new InvCriteriaType();
    }

    /**
     * Create an instance of {@link InvParticipationType }
     * 
     * @return
     *     the new instance of {@link InvParticipationType }
     */
    public InvParticipationType createInvParticipationType() {
        return new InvParticipationType();
    }

    /**
     * Create an instance of {@link InvValueType }
     * 
     * @return
     *     the new instance of {@link InvValueType }
     */
    public InvValueType createInvValueType() {
        return new InvValueType();
    }

    /**
     * Create an instance of {@link NumericType }
     * 
     * @return
     *     the new instance of {@link NumericType }
     */
    public NumericType createNumericType() {
        return new NumericType();
    }

    /**
     * Create an instance of {@link ElrNumericType }
     * 
     * @return
     *     the new instance of {@link ElrNumericType }
     */
    public ElrNumericType createElrNumericType() {
        return new ElrNumericType();
    }

    /**
     * Create an instance of {@link SendToRecipientsType }
     * 
     * @return
     *     the new instance of {@link SendToRecipientsType }
     */
    public SendToRecipientsType createSendToRecipientsType() {
        return new SendToRecipientsType();
    }

    /**
     * Create an instance of {@link IntegerNumericType }
     * 
     * @return
     *     the new instance of {@link IntegerNumericType }
     */
    public IntegerNumericType createIntegerNumericType() {
        return new IntegerNumericType();
    }

    /**
     * Create an instance of {@link EventDateLogicType }
     * 
     * @return
     *     the new instance of {@link EventDateLogicType }
     */
    public EventDateLogicType createEventDateLogicType() {
        return new EventDateLogicType();
    }

    /**
     * Create an instance of {@link InvLogicType }
     * 
     * @return
     *     the new instance of {@link InvLogicType }
     */
    public InvLogicType createInvLogicType() {
        return new InvLogicType();
    }

    /**
     * Create an instance of {@link ElrTimeLogicType }
     * 
     * @return
     *     the new instance of {@link ElrTimeLogicType }
     */
    public ElrTimeLogicType createElrTimeLogicType() {
        return new ElrTimeLogicType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cdc.gov/NEDSS", name = "CodeSystemCode", scope = CodedType.class)
    public JAXBElement<String> createCodedTypeCodeSystemCode(String value) {
        return new JAXBElement<>(_CodedTypeCodeSystemCode_QNAME, String.class, CodedType.class, value);
    }

}
