SELECT MSG_ORGANIZATION.ORG_LOCAL_ID, MSG_ORGANIZATION.ORG_AUTHOR_ID,
       MSG_ORGANIZATION.ORG_EFFECTIVE_TIME, MSG_ORGANIZATION.ORG_NAME_TXT,
       MSG_ORGANIZATION.ORG_ADDR_CITY_TXT, MSG_ORGANIZATION.ORG_ADDR_COMMENT_TXT,
       MSG_ORGANIZATION.ORG_ADDR_COUNTY_CD, MSG_ORGANIZATION.ORG_ADDR_COUNTRY_CD,
       MSG_ORGANIZATION.ORG_ADDR_STATE_CD, MSG_ORGANIZATION.ORG_ADDR_STREET_ADDR1_TXT,
       MSG_ORGANIZATION.ORG_ADDR_STREET_ADDR2_TXT,
       MSG_ORGANIZATION.ORG_ADDR_ZIP_CODE_TXT, MSG_ORGANIZATION.ORG_CLASS_CD,
       MSG_ORGANIZATION.ORG_COMMENT_TXT, MSG_ORGANIZATION.ORG_EMAIL_ADDRESS_TXT,
       MSG_ORGANIZATION.ORG_ID_CLIA_NBR_TXT, MSG_ORGANIZATION.ORG_ID_FACILITY_IDENTIFIER_TXT,
       MSG_ORGANIZATION.ORG_ID_QUICK_CODE_TXT,
       MSG_ORGANIZATION.ORG_PHONE_COMMENT_TXT, MSG_ORGANIZATION.ORG_PHONE_COUNTRY_CODE_TXT,
       MSG_ORGANIZATION.ORG_PHONE_EXTENSION_TXT,
       MSG_ORGANIZATION.ORG_PHONE_NBR_TXT, MSG_ORGANIZATION.ORG_ROLE_CD,
       MSG_ORGANIZATION.ORG_URL_ADDRESS_TXT
FROM   MSG_ORGANIZATION
WHERE MSG_CONTAINER_UID = :MSG_CONTAINER_UID  AND
    ORG_LOCAL_ID IN ( SELECT ANSWER_TXT FROM MSG_ANSWER WHERE MSG_EVENT_ID= :TRT_LOCAL_ID AND MSG_CONTAINER_UID= :MSG_CONTAINER_UID)