-- SELECT TOP (1) MSG_CONTAINER.MSG_CONTAINER_UID, INV_LOCAL_ID, NBS_INTERFACE_UID, RECEIVING_SYSTEM,
--        MSG_CONTAINER.ONGOING_CASE, MSG_CONTAINER.VERSION_CTRL_NBR,DATA_MIGRATION_STATUS
--         ,Replace(Replace(Replace(Convert(VarChar(19), EFFECTIVE_TIME, 121), '-', ''), ' ', ''), ':', '') as EFFECTIVE_TIME
-- FROM  MSG_CONTAINER INNER JOIN MSG_CASE_INVESTIGATION ON
--     MSG_CASE_INVESTIGATION.MSG_CONTAINER_UID = MSG_CONTAINER.MSG_CONTAINER_UID
-- WHERE  (DATA_MIGRATION_STATUS = -1 OR DATA_MIGRATION_STATUS = -2)

SELECT TOP (1) MSG_CONTAINER.MSG_CONTAINER_UID, INV_LOCAL_ID, NBS_INTERFACE_UID, RECEIVING_SYSTEM,
       MSG_CONTAINER.ONGOING_CASE, MSG_CONTAINER.VERSION_CTRL_NBR,DATA_MIGRATION_STATUS
        ,Replace(Replace(Replace(Convert(VarChar(19), EFFECTIVE_TIME, 121), '-', ''), ' ', ''), ':', '') as EFFECTIVE_TIME
FROM  MSG_CONTAINER INNER JOIN MSG_CASE_INVESTIGATION ON
    MSG_CASE_INVESTIGATION.MSG_CONTAINER_UID = MSG_CONTAINER.MSG_CONTAINER_UID
WHERE MSG_CONTAINER.MSG_CONTAINER_UID = 2;