SELECT TOP (1) MSG_CONTAINER.MSG_CONTAINER_UID, INV_LOCAL_ID, NBS_INTERFACE_UID, RECEIVING_SYSTEM,
       MSG_CONTAINER.ONGOING_CASE, MSG_CONTAINER.VERSION_CTRL_NBR,DATA_MIGRATION_STATUS
FROM  MSG_CONTAINER INNER JOIN MSG_CASE_INVESTIGATION ON
        MSG_CASE_INVESTIGATION.MSG_CONTAINER_UID = MSG_CONTAINER.MSG_CONTAINER_UID AND
        MSG_CONTAINER.NBS_INTERFACE_UID = :VALUE_DATA