package gov.cdc.dataprocessing.repository.nbs.srte.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

import java.sql.Timestamp;

@Entity
@Table(name = "Program_area_code")
@Data
/**
 125 - Comment complaint
 3776 - Complex complaint
 6204 - Forcing convert to stream to list complaint
 1141 - Nested complaint
 1118 - Private constructor complaint
 */
@SuppressWarnings({"java:S125", "java:S3776", "java:S6204", "java:S1141", "java:S1118"})
public class ProgramAreaCode {

    @Id
    @Column(name = "prog_area_cd", nullable = false)
    private String progAreaCd;

    @Column(name = "prog_area_desc_txt")
    private String progAreaDescTxt;

    @Column(name = "nbs_uid")
    private Integer nbsUid;

    @Column(name = "status_cd")
    private String statusCd;

    @Column(name = "status_time")
    private Timestamp statusTime;

    @Column(name = "code_set_nm")
    private String codeSetNm;

    @Column(name = "code_seq")
    private Integer codeSeq;

    // Constructors, getters, and setters are generated by Lombok
}