package gov.cdc.nbs.deduplication.seed.model;

import java.util.Arrays;
import java.util.List;

public record MpiPerson(
    String external_id, // person_uid
    String parent_id,
    String birth_date,
    String sex,
    List<Address> address,
    List<Name> name,
    List<Telecom> telecom,
    String race,
    List<Identifier> identifiers) {

  public record Address(
      List<String> line,
      String city,
      String state,
      String postal_code,
      String county) {
  }

  public record Name(
      List<String> given,
      String family,
      List<String> suffix) {
  }

  public record Telecom(String value) {
  }

  public record Identifier(
      String type,
      String value,
      String authority) {
    public static final List<String> SUPPORTED_IDENTIFIERS = Arrays.asList(
        "AC",
        "ACSN",
        "AIN",
        "AM",
        "AMA",
        "AN",
        "ANC",
        "AND",
        "ANON",
        "ANT",
        "APRN",
        "ASID",
        "BA",
        "BC",
        "BCFN",
        "BCT",
        "BR",
        "BRN",
        "BSNR",
        "CAII",
        "CC",
        "CONM",
        "CY",
        "CZ",
        "DC",
        "DCFN",
        "DDS",
        "DEA",
        "DFN",
        "DI",
        "DL",
        "DN",
        "DO",
        "DP",
        "DPM",
        "DR",
        "DS",
        "DSG",
        "EI",
        "EN",
        "ESN",
        "FDR",
        "FDRFN",
        "FGN",
        "FI",
        "FILL",
        "GI",
        "GIN",
        "GL",
        "GN",
        "HC",
        "IND",
        "IRISTEM",
        "JHN",
        "LACSN",
        "LANR",
        "LI",
        "LN",
        "LR",
        "MA",
        "MB",
        "MC",
        "MCD",
        "MCN",
        "MCR",
        "MCT",
        "MD",
        "MI",
        "MR",
        "MRT",
        "MS",
        "NBSNR",
        "NCT",
        "NE",
        "NH",
        "NI",
        "NII",
        "NIIP",
        "NP",
        "NPI",
        "OBI",
        "OD",
        "PA",
        "PC",
        "PCN",
        "PE",
        "PEN",
        "PGN",
        "PHC",
        "PHE",
        "PHO",
        "PI",
        "PIN",
        "PLAC",
        "PN",
        "PNT",
        "PPIN",
        "PPN",
        "PRC",
        "PRN",
        "PT",
        "QA",
        "RI",
        "RN",
        "RPH",
        "RR",
        "RRI",
        "RRP",
        "SAMN",
        "SB",
        "SID",
        "SL",
        "SN",
        "SNBSN",
        "SNO",
        "SP",
        "SR",
        "SRX",
        "SS",
        "STN",
        "TAX",
        "TN",
        "TPR",
        "TRL",
        "U",
        "UDI",
        "UPIN",
        "USID",
        "VN",
        "VP",
        "VS",
        "WC",
        "WCN",
        "WP",
        "XV",
        "XX");
  }

}
