version: '3.7'
services:
  nbsadapter:
    image: raddanki64/eqawsartifacts:nbsadapter
    ports:
      - "8080:8080"
    networks:
      - apps_network
    volumes:
      - /tmp/hl7files:/tmp/hl7files

  phinadapter:
    image: raddanki64/eqawsartifacts:phinadapter
    ports:
      - "8090:8090"
    networks:
      - apps_network

  jwtgenerator:
    image: raddanki64/eqawsartifacts:jwtgenerator
    ports:
      - "8000:8000"
    networks:
      - apps_network

networks:
  apps_network:
      external:
        name: adapter_network



