package gov.cdc.dataprocessing.constant.query;

public class CaseManagementQuery {
    public static final String SELECT_CASE_MANAGEMENT_BY_PH_CASE_UID = """
    SELECT
        case_management_uid AS caseManagementUid,
        public_health_case_uid AS publicHealthCaseUid,
        status_900 AS status900,
        ehars_id AS eharsId,
        epi_link_id AS epiLinkId,
        field_foll_up_ooj_outcome AS fieldFollUpOojOutcome,
        field_record_number AS fieldRecordNumber,
        fld_foll_up_dispo AS fldFollUpDispo,
        fld_foll_up_dispo_date AS fldFollUpDispoDate,
        fld_foll_up_exam_date AS fldFollUpExamDate,
        fld_foll_up_expected_date AS fldFollUpExpectedDate,
        fld_foll_up_expected_in AS fldFollUpExpectedIn,
        fld_foll_up_internet_outcome AS fldFollUpInternetOutcome,
        fld_foll_up_notification_plan AS fldFollUpNotificationPlan,
        fld_foll_up_prov_diagnosis AS fldFollUpProvDiagnosis,
        fld_foll_up_prov_exm_reason AS fldFollUpProvExmReason,
        init_foll_up AS initFollUp,
        init_foll_up_clinic_code AS initFollUpClinicCode,
        init_foll_up_closed_date AS initFollUpClosedDate,
        init_foll_up_notifiable AS initFollUpNotifiable,
        internet_foll_up AS internetFollUp,
        ooj_agency AS oojAgency,
        ooj_due_date AS oojDueDate,
        ooj_number AS oojNumber,
        pat_intv_status_cd AS patIntvStatusCd,
        subj_complexion AS subjComplexion,
        subj_hair AS subjHair,
        subj_height AS subjHeight,
        subj_oth_idntfyng_info AS subjOthIdntfyngInfo,
        subj_size_build AS subjSizeBuild,
        surv_closed_date AS survClosedDate,
        surv_patient_foll_up AS survPatientFollUp,
        surv_prov_diagnosis AS survProvDiagnosis,
        surv_prov_exm_reason AS survProvExmReason,
        surv_provider_contact AS survProviderContact,
        act_ref_type_cd AS actRefTypeCd,
        initiating_agncy AS initiatingAgncy,
        ooj_initg_agncy_outc_due_date AS oojInitgAgncyOutcDueDate,
        ooj_initg_agncy_outc_snt_date AS oojInitgAgncyOutcSntDate,
        ooj_initg_agncy_recd_date AS oojInitgAgncyRecdDate,
        case_review_status AS caseReviewStatus,
        surv_assigned_date AS survAssignedDate,
        foll_up_assigned_date AS follUpAssignedDate,
        init_foll_up_assigned_date AS initFollUpAssignedDate,
        interview_assigned_date AS interviewAssignedDate,
        init_interview_assigned_date AS initInterviewAssignedDate,
        case_closed_date AS caseClosedDate,
        case_review_status_date AS caseReviewStatusDate
    FROM case_management
    WHERE public_health_case_uid = :publicHealthCaseUid
""";

    public static final String MERGE_CASE_MANAGEMENT = """
MERGE INTO case_management AS target
USING (
    SELECT
        :caseManagementUid AS case_management_uid,
        :publicHealthCaseUid AS public_health_case_uid,
        :status900 AS status_900,
        :eharsId AS ehars_id,
        :epiLinkId AS epi_link_id,
        :fieldFollUpOojOutcome AS field_foll_up_ooj_outcome,
        :fieldRecordNumber AS field_record_number,
        :fldFollUpDispo AS fld_foll_up_dispo,
        :fldFollUpDispoDate AS fld_foll_up_dispo_date,
        :fldFollUpExamDate AS fld_foll_up_exam_date,
        :fldFollUpExpectedDate AS fld_foll_up_expected_date,
        :fldFollUpExpectedIn AS fld_foll_up_expected_in,
        :fldFollUpInternetOutcome AS fld_foll_up_internet_outcome,
        :fldFollUpNotificationPlan AS fld_foll_up_notification_plan,
        :fldFollUpProvDiagnosis AS fld_foll_up_prov_diagnosis,
        :fldFollUpProvExmReason AS fld_foll_up_prov_exm_reason,
        :initFollUp AS init_foll_up,
        :initFollUpClinicCode AS init_foll_up_clinic_code,
        :initFollUpClosedDate AS init_foll_up_closed_date,
        :initFollUpNotifiable AS init_foll_up_notifiable,
        :internetFollUp AS internet_foll_up,
        :oojAgency AS ooj_agency,
        :oojDueDate AS ooj_due_date,
        :oojNumber AS ooj_number,
        :patIntvStatusCd AS pat_intv_status_cd,
        :subjComplexion AS subj_complexion,
        :subjHair AS subj_hair,
        :subjHeight AS subj_height,
        :subjOthIdntfyngInfo AS subj_oth_idntfyng_info,
        :subjSizeBuild AS subj_size_build,
        :survClosedDate AS surv_closed_date,
        :survPatientFollUp AS surv_patient_foll_up,
        :survProvDiagnosis AS surv_prov_diagnosis,
        :survProvExmReason AS surv_prov_exm_reason,
        :survProviderContact AS surv_provider_contact,
        :actRefTypeCd AS act_ref_type_cd,
        :initiatingAgncy AS initiating_agncy,
        :oojInitgAgncyOutcDueDate AS ooj_initg_agncy_outc_due_date,
        :oojInitgAgncyOutcSntDate AS ooj_initg_agncy_outc_snt_date,
        :oojInitgAgncyRecdDate AS ooj_initg_agncy_recd_date,
        :caseReviewStatus AS case_review_status,
        :survAssignedDate AS surv_assigned_date,
        :follUpAssignedDate AS foll_up_assigned_date,
        :initFollUpAssignedDate AS init_foll_up_assigned_date,
        :interviewAssignedDate AS interview_assigned_date,
        :initInterviewAssignedDate AS init_interview_assigned_date,
        :caseClosedDate AS case_closed_date,
        :caseReviewStatusDate AS case_review_status_date
) AS source
ON target.case_management_uid = source.case_management_uid
WHEN MATCHED THEN UPDATE SET
    public_health_case_uid = source.public_health_case_uid,
    status_900 = source.status_900,
    ehars_id = source.ehars_id,
    epi_link_id = source.epi_link_id,
    field_foll_up_ooj_outcome = source.field_foll_up_ooj_outcome,
    field_record_number = source.field_record_number,
    fld_foll_up_dispo = source.fld_foll_up_dispo,
    fld_foll_up_dispo_date = source.fld_foll_up_dispo_date,
    fld_foll_up_exam_date = source.fld_foll_up_exam_date,
    fld_foll_up_expected_date = source.fld_foll_up_expected_date,
    fld_foll_up_expected_in = source.fld_foll_up_expected_in,
    fld_foll_up_internet_outcome = source.fld_foll_up_internet_outcome,
    fld_foll_up_notification_plan = source.fld_foll_up_notification_plan,
    fld_foll_up_prov_diagnosis = source.fld_foll_up_prov_diagnosis,
    fld_foll_up_prov_exm_reason = source.fld_foll_up_prov_exm_reason,
    init_foll_up = source.init_foll_up,
    init_foll_up_clinic_code = source.init_foll_up_clinic_code,
    init_foll_up_closed_date = source.init_foll_up_closed_date,
    init_foll_up_notifiable = source.init_foll_up_notifiable,
    internet_foll_up = source.internet_foll_up,
    ooj_agency = source.ooj_agency,
    ooj_due_date = source.ooj_due_date,
    ooj_number = source.ooj_number,
    pat_intv_status_cd = source.pat_intv_status_cd,
    subj_complexion = source.subj_complexion,
    subj_hair = source.subj_hair,
    subj_height = source.subj_height,
    subj_oth_idntfyng_info = source.subj_oth_idntfyng_info,
    subj_size_build = source.subj_size_build,
    surv_closed_date = source.surv_closed_date,
    surv_patient_foll_up = source.surv_patient_foll_up,
    surv_prov_diagnosis = source.surv_prov_diagnosis,
    surv_prov_exm_reason = source.surv_prov_exm_reason,
    surv_provider_contact = source.surv_provider_contact,
    act_ref_type_cd = source.act_ref_type_cd,
    initiating_agncy = source.initiating_agncy,
    ooj_initg_agncy_outc_due_date = source.ooj_initg_agncy_outc_due_date,
    ooj_initg_agncy_outc_snt_date = source.ooj_initg_agncy_outc_snt_date,
    ooj_initg_agncy_recd_date = source.ooj_initg_agncy_recd_date,
    case_review_status = source.case_review_status,
    surv_assigned_date = source.surv_assigned_date,
    foll_up_assigned_date = source.foll_up_assigned_date,
    init_foll_up_assigned_date = source.init_foll_up_assigned_date,
    interview_assigned_date = source.interview_assigned_date,
    init_interview_assigned_date = source.init_interview_assigned_date,
    case_closed_date = source.case_closed_date,
    case_review_status_date = source.case_review_status_date
WHEN NOT MATCHED THEN INSERT (
    public_health_case_uid,
    status_900,
    ehars_id,
    epi_link_id,
    field_foll_up_ooj_outcome,
    field_record_number,
    fld_foll_up_dispo,
    fld_foll_up_dispo_date,
    fld_foll_up_exam_date,
    fld_foll_up_expected_date,
    fld_foll_up_expected_in,
    fld_foll_up_internet_outcome,
    fld_foll_up_notification_plan,
    fld_foll_up_prov_diagnosis,
    fld_foll_up_prov_exm_reason,
    init_foll_up,
    init_foll_up_clinic_code,
    init_foll_up_closed_date,
    init_foll_up_notifiable,
    internet_foll_up,
    ooj_agency,
    ooj_due_date,
    ooj_number,
    pat_intv_status_cd,
    subj_complexion,
    subj_hair,
    subj_height,
    subj_oth_idntfyng_info,
    subj_size_build,
    surv_closed_date,
    surv_patient_foll_up,
    surv_prov_diagnosis,
    surv_prov_exm_reason,
    surv_provider_contact,
    act_ref_type_cd,
    initiating_agncy,
    ooj_initg_agncy_outc_due_date,
    ooj_initg_agncy_outc_snt_date,
    ooj_initg_agncy_recd_date,
    case_review_status,
    surv_assigned_date,
    foll_up_assigned_date,
    init_foll_up_assigned_date,
    interview_assigned_date,
    init_interview_assigned_date,
    case_closed_date,
    case_review_status_date
) VALUES (
    source.public_health_case_uid,
    source.status_900,
    source.ehars_id,
    source.epi_link_id,
    source.field_foll_up_ooj_outcome,
    source.field_record_number,
    source.fld_foll_up_dispo,
    source.fld_foll_up_dispo_date,
    source.fld_foll_up_exam_date,
    source.fld_foll_up_expected_date,
    source.fld_foll_up_expected_in,
    source.fld_foll_up_internet_outcome,
    source.fld_foll_up_notification_plan,
    source.fld_foll_up_prov_diagnosis,
    source.fld_foll_up_prov_exm_reason,
    source.init_foll_up,
    source.init_foll_up_clinic_code,
    source.init_foll_up_closed_date,
    source.init_foll_up_notifiable,
    source.internet_foll_up,
    source.ooj_agency,
    source.ooj_due_date,
    source.ooj_number,
    source.pat_intv_status_cd,
    source.subj_complexion,
    source.subj_hair,
    source.subj_height,
    source.subj_oth_idntfyng_info,
    source.subj_size_build,
    source.surv_closed_date,
    source.surv_patient_foll_up,
    source.surv_prov_diagnosis,
    source.surv_prov_exm_reason,
    source.surv_provider_contact,
    source.act_ref_type_cd,
    source.initiating_agncy,
    source.ooj_initg_agncy_outc_due_date,
    source.ooj_initg_agncy_outc_snt_date,
    source.ooj_initg_agncy_recd_date,
    source.case_review_status,
    source.surv_assigned_date,
    source.foll_up_assigned_date,
    source.init_foll_up_assigned_date,
    source.interview_assigned_date,
    source.init_interview_assigned_date,
    source.case_closed_date,
    source.case_review_status_date
);
""";

}
