package gov.cdc.dataprocessing.constant.query;

public class NotificationQuery {
    public static final String INSERT_SQL_NOTIFICATION = """
    INSERT INTO Notification (
        notification_uid, activity_duration_amt, activity_duration_unit_cd, activity_from_time, activity_to_time,
        add_reason_cd, add_time, add_user_id, case_class_cd, case_condition_cd,
        cd, cd_desc_txt, confidentiality_cd, confidentiality_desc_txt, confirmation_method_cd,
        effective_duration_amt, effective_duration_unit_cd, effective_from_time, effective_to_time, jurisdiction_cd,
        last_chg_reason_cd, last_chg_time, last_chg_user_id, local_id, message_txt,
        method_cd, method_desc_txt, mmwr_week, mmwr_year, nedss_version_nbr,
        prog_area_cd, reason_cd, reason_desc_txt, record_count, record_status_cd,
        record_status_time, repeat_nbr, rpt_sent_time, rpt_source_cd, rpt_source_type_cd,
        status_cd, status_time, txt, user_affiliation_txt, program_jurisdiction_oid,
        shared_ind, version_ctrl_nbr, auto_resend_ind, export_receiving_facility_uid, nbs_interface_uid
    ) VALUES (
        :notification_uid, :activity_duration_amt, :activity_duration_unit_cd, :activity_from_time, :activity_to_time,
        :add_reason_cd, :add_time, :add_user_id, :case_class_cd, :case_condition_cd,
        :cd, :cd_desc_txt, :confidentiality_cd, :confidentiality_desc_txt, :confirmation_method_cd,
        :effective_duration_amt, :effective_duration_unit_cd, :effective_from_time, :effective_to_time, :jurisdiction_cd,
        :last_chg_reason_cd, :last_chg_time, :last_chg_user_id, :local_id, :message_txt,
        :method_cd, :method_desc_txt, :mmwr_week, :mmwr_year, :nedss_version_nbr,
        :prog_area_cd, :reason_cd, :reason_desc_txt, :record_count, :record_status_cd,
        :record_status_time, :repeat_nbr, :rpt_sent_time, :rpt_source_cd, :rpt_source_type_cd,
        :status_cd, :status_time, :txt, :user_affiliation_txt, :program_jurisdiction_oid,
        :shared_ind, :version_ctrl_nbr, :auto_resend_ind, :export_receiving_facility_uid, :nbs_interface_uid
    )
""";

    public static final String UPDATE_SQL_NOTIFICATION = """ 
    UPDATE Notification SET
    activity_duration_amt = :activity_duration_amt,
    activity_duration_unit_cd = :activity_duration_unit_cd,
    activity_from_time = :activity_from_time,
    activity_to_time = :activity_to_time,
    add_reason_cd = :add_reason_cd,
    add_time = :add_time,
    add_user_id = :add_user_id,
    case_class_cd = :case_class_cd,
    case_condition_cd = :case_condition_cd,
    cd = :cd,
    cd_desc_txt = :cd_desc_txt,
    confidentiality_cd = :confidentiality_cd,
    confidentiality_desc_txt = :confidentiality_desc_txt,
    confirmation_method_cd = :confirmation_method_cd,
    effective_duration_amt = :effective_duration_amt,
    effective_duration_unit_cd = :effective_duration_unit_cd,
    effective_from_time = :effective_from_time,
    effective_to_time = :effective_to_time,
    jurisdiction_cd = :jurisdiction_cd,
    last_chg_reason_cd = :last_chg_reason_cd,
    last_chg_time = :last_chg_time,
    last_chg_user_id = :last_chg_user_id,
    local_id = :local_id,
    message_txt = :message_txt,
    method_cd = :method_cd,
    method_desc_txt = :method_desc_txt,
    mmwr_week = :mmwr_week,
    mmwr_year = :mmwr_year,
    nedss_version_nbr = :nedss_version_nbr,
    prog_area_cd = :prog_area_cd,
    reason_cd = :reason_cd,
    reason_desc_txt = :reason_desc_txt,
    record_count = :record_count,
    record_status_cd = :record_status_cd,
    record_status_time = :record_status_time,
    repeat_nbr = :repeat_nbr,
    rpt_sent_time = :rpt_sent_time,
    rpt_source_cd = :rpt_source_cd,
    rpt_source_type_cd = :rpt_source_type_cd,
    status_cd = :status_cd,
    status_time = :status_time,
    txt = :txt,
    user_affiliation_txt = :user_affiliation_txt,
    program_jurisdiction_oid = :program_jurisdiction_oid,
    shared_ind = :shared_ind,
    version_ctrl_nbr = :version_ctrl_nbr,
    auto_resend_ind = :auto_resend_ind,
    export_receiving_facility_uid = :export_receiving_facility_uid,
    nbs_interface_uid = :nbs_interface_uid
    WHERE notification_uid = :notification_uid
    """;

    public static final String SELECT_NOTIFICATION_BY_ID = """
SELECT
    notification_uid                  AS notificationUid,
    activity_duration_amt            AS activityDurationAmt,
    activity_duration_unit_cd        AS activityDurationUnitCd,
    activity_from_time               AS activityFromTime,
    activity_to_time                 AS activityToTime,
    add_reason_cd                    AS addReasonCd,
    add_time                         AS addTime,
    add_user_id                      AS addUserId,
    case_class_cd                    AS caseClassCd,
    case_condition_cd                AS caseConditionCd,
    cd                               AS cd,
    cd_desc_txt                      AS cdDescTxt,
    confidentiality_cd               AS confidentialityCd,
    confidentiality_desc_txt        AS confidentialityDescTxt,
    confirmation_method_cd           AS confirmationMethodCd,
    effective_duration_amt           AS effectiveDurationAmt,
    effective_duration_unit_cd       AS effectiveDurationUnitCd,
    effective_from_time              AS effectiveFromTime,
    effective_to_time                AS effectiveToTime,
    jurisdiction_cd                  AS jurisdictionCd,
    last_chg_reason_cd              AS lastChgReasonCd,
    last_chg_time                   AS lastChgTime,
    last_chg_user_id               AS lastChgUserId,
    local_id                        AS localId,
    message_txt                     AS messageTxt,
    method_cd                       AS methodCd,
    method_desc_txt                 AS methodDescTxt,
    mmwr_week                       AS mmwrWeek,
    mmwr_year                       AS mmwrYear,
    nedss_version_nbr              AS nedssVersionNbr,
    prog_area_cd                   AS progAreaCd,
    reason_cd                      AS reasonCd,
    reason_desc_txt                AS reasonDescTxt,
    record_count                   AS recordCount,
    record_status_cd               AS recordStatusCd,
    record_status_time             AS recordStatusTime,
    repeat_nbr                     AS repeatNbr,
    rpt_sent_time                  AS rptSentTime,
    rpt_source_cd                  AS rptSourceCd,
    rpt_source_type_cd             AS rptSourceTypeCd,
    status_cd                      AS statusCd,
    status_time                    AS statusTime,
    txt                            AS txt,
    user_affiliation_txt           AS userAffiliationTxt,
    program_jurisdiction_oid       AS programJurisdictionOid,
    shared_ind                     AS sharedInd,
    version_ctrl_nbr               AS versionCtrlNbr,
    auto_resend_ind                AS autoResendInd,
    export_receiving_facility_uid AS exportReceivingFacilityUid,
    nbs_interface_uid              AS nbsInterfaceUid
FROM Notification
WHERE notification_uid = :notificationUid
""";

}
