package gov.cdc.dataprocessing.constant.query;

public class PublicHealthCaseQuery {
    public static final String INSERT_PHC = """
            INSERT INTO Public_health_case (
                 public_health_case_uid,
                 activity_duration_amt,
                 activity_duration_unit_cd,
                 activity_from_time,
                 activity_to_time,
                 add_reason_cd,
                 add_time,
                 add_user_id,
                 case_class_cd,
                 case_type_cd,
                 cd,
                 cd_desc_txt,
                 cd_system_cd,
                 cd_system_desc_txt,
                 confidentiality_cd,
                 confidentiality_desc_txt,
                 detection_method_cd,
                 detection_method_desc_txt,
                 diagnosis_time,
                 disease_imported_cd,
                 disease_imported_desc_txt,
                 effective_duration_amt,
                 effective_duration_unit_cd,
                 effective_from_time,
                 effective_to_time,
                 group_case_cnt,
                 investigation_status_cd,
                 jurisdiction_cd,
                 last_chg_reason_cd,
                 last_chg_time,
                 last_chg_user_id,
                 local_id,
                 mmwr_week,
                 mmwr_year,
                 outbreak_ind,
                 outbreak_from_time,
                 outbreak_to_time,
                 outbreak_name,
                 outcome_cd,
                 pat_age_at_onset,
                 pat_age_at_onset_unit_cd,
                 patient_group_id,
                 prog_area_cd,
                 record_status_cd,
                 record_status_time,
                 repeat_nbr,
                 rpt_cnty_cd,
                 rpt_form_cmplt_time,
                 rpt_source_cd,
                 rpt_source_cd_desc_txt,
                 rpt_to_county_time,
                 rpt_to_state_time,
                 status_cd,
                 status_time,
                 transmission_mode_cd,
                 transmission_mode_desc_txt,
                 txt,
                 user_affiliation_txt,
                 program_jurisdiction_oid,
                 shared_ind,
                 version_ctrl_nbr,
                 investigator_assigned_time,
                 hospitalized_ind_cd,
                 hospitalized_admin_time,
                 hospitalized_discharge_time,
                 hospitalized_duration_amt,
                 pregnant_ind_cd,
                 day_care_ind_cd,
                 food_handler_ind_cd,
                 imported_country_cd,
                 imported_state_cd,
                 imported_city_desc_txt,
                 imported_county_cd,
                 deceased_time,
                 count_interval_cd,
                 priority_cd,
                 contact_inv_txt,
                 infectious_from_date,
                 infectious_to_date,
                 contact_inv_status_cd,
                 referral_basis_cd,
                 curr_process_state_cd,
                 inv_priority_cd,
                 coinfection_id
             ) VALUES (
                 :publicHealthCaseUid,
                 :activityDurationAmt,
                 :activityDurationUnitCd,
                 :activityFromTime,
                 :activityToTime,
                 :addReasonCd,
                 :addTime,
                 :addUserId,
                 :caseClassCd,
                 :caseTypeCd,
                 :cd,
                 :cdDescTxt,
                 :cdSystemCd,
                 :cdSystemDescTxt,
                 :confidentialityCd,
                 :confidentialityDescTxt,
                 :detectionMethodCd,
                 :detectionMethodDescTxt,
                 :diagnosisTime,
                 :diseaseImportedCd,
                 :diseaseImportedDescTxt,
                 :effectiveDurationAmt,
                 :effectiveDurationUnitCd,
                 :effectiveFromTime,
                 :effectiveToTime,
                 :groupCaseCnt,
                 :investigationStatusCd,
                 :jurisdictionCd,
                 :lastChgReasonCd,
                 :lastChgTime,
                 :lastChgUserId,
                 :localId,
                 :mmwrWeek,
                 :mmwrYear,
                 :outbreakInd,
                 :outbreakFromTime,
                 :outbreakToTime,
                 :outbreakName,
                 :outcomeCd,
                 :patAgeAtOnset,
                 :patAgeAtOnsetUnitCd,
                 :patientGroupId,
                 :progAreaCd,
                 :recordStatusCd,
                 :recordStatusTime,
                 :repeatNbr,
                 :rptCntyCd,
                 :rptFormCmpltTime,
                 :rptSourceCd,
                 :rptSourceCdDescTxt,
                 :rptToCountyTime,
                 :rptToStateTime,
                 :statusCd,
                 :statusTime,
                 :transmissionModeCd,
                 :transmissionModeDescTxt,
                 :txt,
                 :userAffiliationTxt,
                 :programJurisdictionOid,
                 :sharedInd,
                 :versionCtrlNbr,
                 :investigatorAssignedTime,
                 :hospitalizedIndCd,
                 :hospitalizedAdminTime,
                 :hospitalizedDischargeTime,
                 :hospitalizedDurationAmt,
                 :pregnantIndCd,
                 :dayCareIndCd,
                 :foodHandlerIndCd,
                 :importedCountryCd,
                 :importedStateCd,
                 :importedCityDescTxt,
                 :importedCountyCd,
                 :deceasedTime,
                 :countIntervalCd,
                 :priorityCd,
                 :contactInvTxt,
                 :infectiousFromDate,
                 :infectiousToDate,
                 :contactInvStatusCd,
                 :referralBasisCd,
                 :currProcessStateCd,
                 :invPriorityCd,
                 :coinfectionId
             )
            """;

    public static final String UPDATE_PHC = """
UPDATE Public_health_case SET
    activity_duration_amt = :activityDurationAmt,
    activity_duration_unit_cd = :activityDurationUnitCd,
    activity_from_time = :activityFromTime,
    activity_to_time = :activityToTime,
    add_reason_cd = :addReasonCd,
    add_time = :addTime,
    add_user_id = :addUserId,
    case_class_cd = :caseClassCd,
    case_type_cd = :caseTypeCd,
    cd = :cd,
    cd_desc_txt = :cdDescTxt,
    cd_system_cd = :cdSystemCd,
    cd_system_desc_txt = :cdSystemDescTxt,
    confidentiality_cd = :confidentialityCd,
    confidentiality_desc_txt = :confidentialityDescTxt,
    detection_method_cd = :detectionMethodCd,
    detection_method_desc_txt = :detectionMethodDescTxt,
    diagnosis_time = :diagnosisTime,
    disease_imported_cd = :diseaseImportedCd,
    disease_imported_desc_txt = :diseaseImportedDescTxt,
    effective_duration_amt = :effectiveDurationAmt,
    effective_duration_unit_cd = :effectiveDurationUnitCd,
    effective_from_time = :effectiveFromTime,
    effective_to_time = :effectiveToTime,
    group_case_cnt = :groupCaseCnt,
    investigation_status_cd = :investigationStatusCd,
    jurisdiction_cd = :jurisdictionCd,
    last_chg_reason_cd = :lastChgReasonCd,
    last_chg_time = :lastChgTime,
    last_chg_user_id = :lastChgUserId,
    local_id = :localId,
    mmwr_week = :mmwrWeek,
    mmwr_year = :mmwrYear,
    outbreak_ind = :outbreakInd,
    outbreak_from_time = :outbreakFromTime,
    outbreak_to_time = :outbreakToTime,
    outbreak_name = :outbreakName,
    outcome_cd = :outcomeCd,
    pat_age_at_onset = :patAgeAtOnset,
    pat_age_at_onset_unit_cd = :patAgeAtOnsetUnitCd,
    patient_group_id = :patientGroupId,
    prog_area_cd = :progAreaCd,
    record_status_cd = :recordStatusCd,
    record_status_time = :recordStatusTime,
    repeat_nbr = :repeatNbr,
    rpt_cnty_cd = :rptCntyCd,
    rpt_form_cmplt_time = :rptFormCmpltTime,
    rpt_source_cd = :rptSourceCd,
    rpt_source_cd_desc_txt = :rptSourceCdDescTxt,
    rpt_to_county_time = :rptToCountyTime,
    rpt_to_state_time = :rptToStateTime,
    status_cd = :statusCd,
    status_time = :statusTime,
    transmission_mode_cd = :transmissionModeCd,
    transmission_mode_desc_txt = :transmissionModeDescTxt,
    txt = :txt,
    user_affiliation_txt = :userAffiliationTxt,
    program_jurisdiction_oid = :programJurisdictionOid,
    shared_ind = :sharedInd,
    version_ctrl_nbr = :versionCtrlNbr,
    investigator_assigned_time = :investigatorAssignedTime,
    hospitalized_ind_cd = :hospitalizedIndCd,
    hospitalized_admin_time = :hospitalizedAdminTime,
    hospitalized_discharge_time = :hospitalizedDischargeTime,
    hospitalized_duration_amt = :hospitalizedDurationAmt,
    pregnant_ind_cd = :pregnantIndCd,
    day_care_ind_cd = :dayCareIndCd,
    food_handler_ind_cd = :foodHandlerIndCd,
    imported_country_cd = :importedCountryCd,
    imported_state_cd = :importedStateCd,
    imported_city_desc_txt = :importedCityDescTxt,
    imported_county_cd = :importedCountyCd,
    deceased_time = :deceasedTime,
    count_interval_cd = :countIntervalCd,
    priority_cd = :priorityCd,
    contact_inv_txt = :contactInvTxt,
    infectious_from_date = :infectiousFromDate,
    infectious_to_date = :infectiousToDate,
    contact_inv_status_cd = :contactInvStatusCd,
    referral_basis_cd = :referralBasisCd,
    curr_process_state_cd = :currProcessStateCd,
    inv_priority_cd = :invPriorityCd,
    coinfection_id = :coinfectionId
WHERE public_health_case_uid = :publicHealthCaseUid
""";


    public static final String SELECT_PHC_BY_UID = """
SELECT
    public_health_case_uid AS publicHealthCaseUid,
    activity_duration_amt AS activityDurationAmt,
    activity_duration_unit_cd AS activityDurationUnitCd,
    activity_from_time AS activityFromTime,
    activity_to_time AS activityToTime,
    add_reason_cd AS addReasonCd,
    add_time AS addTime,
    add_user_id AS addUserId,
    case_class_cd AS caseClassCd,
    case_type_cd AS caseTypeCd,
    cd AS cd,
    cd_desc_txt AS cdDescTxt,
    cd_system_cd AS cdSystemCd,
    cd_system_desc_txt AS cdSystemDescTxt,
    confidentiality_cd AS confidentialityCd,
    confidentiality_desc_txt AS confidentialityDescTxt,
    detection_method_cd AS detectionMethodCd,
    detection_method_desc_txt AS detectionMethodDescTxt,
    diagnosis_time AS diagnosisTime,
    disease_imported_cd AS diseaseImportedCd,
    disease_imported_desc_txt AS diseaseImportedDescTxt,
    effective_duration_amt AS effectiveDurationAmt,
    effective_duration_unit_cd AS effectiveDurationUnitCd,
    effective_from_time AS effectiveFromTime,
    effective_to_time AS effectiveToTime,
    group_case_cnt AS groupCaseCnt,
    investigation_status_cd AS investigationStatusCd,
    jurisdiction_cd AS jurisdictionCd,
    last_chg_reason_cd AS lastChgReasonCd,
    last_chg_time AS lastChgTime,
    last_chg_user_id AS lastChgUserId,
    local_id AS localId,
    mmwr_week AS mmwrWeek,
    mmwr_year AS mmwrYear,
    outbreak_ind AS outbreakInd,
    outbreak_from_time AS outbreakFromTime,
    outbreak_to_time AS outbreakToTime,
    outbreak_name AS outbreakName,
    outcome_cd AS outcomeCd,
    pat_age_at_onset AS patAgeAtOnset,
    pat_age_at_onset_unit_cd AS patAgeAtOnsetUnitCd,
    patient_group_id AS patientGroupId,
    prog_area_cd AS progAreaCd,
    record_status_cd AS recordStatusCd,
    record_status_time AS recordStatusTime,
    repeat_nbr AS repeatNbr,
    rpt_cnty_cd AS rptCntyCd,
    rpt_form_cmplt_time AS rptFormCmpltTime,
    rpt_source_cd AS rptSourceCd,
    rpt_source_cd_desc_txt AS rptSourceCdDescTxt,
    rpt_to_county_time AS rptToCountyTime,
    rpt_to_state_time AS rptToStateTime,
    status_cd AS statusCd,
    status_time AS statusTime,
    transmission_mode_cd AS transmissionModeCd,
    transmission_mode_desc_txt AS transmissionModeDescTxt,
    txt AS txt,
    user_affiliation_txt AS userAffiliationTxt,
    program_jurisdiction_oid AS programJurisdictionOid,
    shared_ind AS sharedInd,
    version_ctrl_nbr AS versionCtrlNbr,
    investigator_assigned_time AS investigatorAssignedTime,
    hospitalized_ind_cd AS hospitalizedIndCd,
    hospitalized_admin_time AS hospitalizedAdminTime,
    hospitalized_discharge_time AS hospitalizedDischargeTime,
    hospitalized_duration_amt AS hospitalizedDurationAmt,
    pregnant_ind_cd AS pregnantIndCd,
    day_care_ind_cd AS dayCareIndCd,
    food_handler_ind_cd AS foodHandlerIndCd,
    imported_country_cd AS importedCountryCd,
    imported_state_cd AS importedStateCd,
    imported_city_desc_txt AS importedCityDescTxt,
    imported_county_cd AS importedCountyCd,
    deceased_time AS deceasedTime,
    count_interval_cd AS countIntervalCd,
    priority_cd AS priorityCd,
    contact_inv_txt AS contactInvTxt,
    infectious_from_date AS infectiousFromDate,
    infectious_to_date AS infectiousToDate,
    contact_inv_status_cd AS contactInvStatusCd,
    referral_basis_cd AS referralBasisCd,
    curr_process_state_cd AS currProcessStateCd,
    inv_priority_cd AS invPriorityCd,
    coinfection_id AS coinfectionId
FROM Public_health_case
WHERE public_health_case_uid = :publicHealthCaseUid
""";

}
