spring:
  application:
    name: phinadapter

logging:
  file: logs/phinadapter.log
  
  pattern:
    console: "%d %-5level %logger : %file-%line : %msg%n"
    file:    "%d %-5level [%thread] %logger : [ramesh] : %msg%n"
    
  level:
    com.apps.restfulApp.api.controller: ERROR

---
spring:
  profiles: local
  
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: vault_odsedb_url
    username: vault_odsedb_username
    password: vault_odsedb_password

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

hashivault:
  enabled: true
  authendpoint:    http://vault:8200/v1/auth/cert/login
  secretsendpoint: http://vault:8200/v1/secrets/${spring.application.name}/${spring.profiles.active}

jwt:
  enabled: vault_jwt_enabled
  endpoint: vault_jwt_endpoint
  seed: vault_jwt_seed

thread-pooling:
  core-pool-size: 25
  max-pool-size: 300

server:
  port: 8090
  tomcat:
    accept-count: 100
    max-connections: 10000
    max-threads: 200
