server:
  port: 8084
  servlet:
    context-path: /data

info:
  app:
    name: SRTE Data Exchange
    version: 1.0.0
    description: SRTE Data Exchange Service

management:
  info:
    build:
      enabled: true
    java:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      roles: ADMIN
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info"
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: srte-data-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RTI_CACHE_AUTH_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
auth:
  token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  introspect-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token/introspect

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${NBS_DBUSER}
    password: ${NBS_DBPASSWORD}
    nbs:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_MSGOUTE;encrypt=true;trustServerCertificate=true;
    odse:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;
    srte:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_SRTE;encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

---
dcserver:
  host: ${RTI_CACHE_SERVER_HOST:localhost:8085}
