server:
  port: 8083

spring:
  application.name: deduplication
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        timezone:
          default_storage: NORMALIZE
  datasource:
    deduplication:
      url: ${DEDUPLICATION_DB_URL}
      username: ${DEDUPLICATION_DB_USERNAME}
      password: ${DEDUPLICATION_DB_PASSWORD}
    nbs:
      url: ${NBS_DB_URL}
      username: ${NBS_DB_USERNAME}
      password: ${NBS_DB_PASSWORD}
    mpi:
      url: ${MPI_DB_URL}
      username: ${MPI_DB_USERNAME}
      password: ${MPI_DB_PASSWORD}

recordLinkage:
  url: http://localhost:8080

batch:
  chunk:
    size:
      step1: 100
      step2: 1000
