server:
  port: 8083
  servlet:
    context-path: /nbs/api/deduplication

spring:
  application.name: deduplication
  jackson.serialization.indent-output: true
  kafka.bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          jwk-set-uri:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        timezone:
          default_storage: NORMALIZE
  datasource:
    deduplication:
      url: ${DEDUPLICATION_DB_URL}
      username: ${DEDUPLICATION_DB_USERNAME}
      password: ${DEDUPLICATION_DB_PASSWORD}
    nbs:
      url: ${NBS_DB_URL}
      username: ${NBS_DB_USERNAME}
      password: ${NBS_DB_PASSWORD}
    mpi:
      url: ${MPI_DB_URL}
      username: ${MPI_DB_USERNAME}
      password: ${MPI_DB_PASSWORD}

  main:
    allow-circular-references: true

nbs:
  security:
    tokenSecret:
    tokenIssuer: gov.cdc.nbs
    tokenExpirationMillis: 1800000 # 30 minutes
    oidc:
      # toggles the validation of users provided jwt token
      enabled: false
    paths:
      ignored: # routes that are excluded from security
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-resources/**
        - /match
        - /health

deduplication:
  # url for Record Linker API
  recordLinker:
    url: ${RECORD_LINKER_URL:http://localhost:8070}
  algorithm:
    # should data elements and algorithm updates be pushed to Record Linker API
    updateRecordLinker: ${ALGORITHM_UPDATE_RL:false}
    allowMultipleMatches: false
  sync:
    enabled: ${SYNC_ENABLED:false}
  batch:
    schedule:
      enabled: ${BATCH_ENABLED:false}
      cron: "0 0 1 * * ?" # run daily at 1 AM
    processing:
      total: 10000 # how many records to process per job execution
      chunk: 100 # how many are processed at a time
  seed:
    mpiInsertSize: 100 # how many records to insert into MPI at a time (max 100)
    deduplicationInsertSize: 1000 # how many records to insert into deduplication db at a time

kafka:
  topics:
    person: nbs_Person
