spring.application.name=mpi-dataSyncer
server.port=8081

# activemq
spring.activemq.broker-url=vm://localhost
spring.activemq.embedded=true
batch.size =10
sync.mode =false

sync.fixedRate=6000

use.linker.api = true
linker.seed.url=http://localhost:8080/seed


# kafka
kafka.consumer.enabled=false
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mpiDataSyncerGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Nbs DataSource (MSSQL for nbs_person)
spring.datasource.nbs.url=jdbc:sqlserver://localhost:1433;databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;
spring.datasource.nbs.username=sa
spring.datasource.nbs.password=fake.fake.fake.1234
spring.datasource.nbs.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.nbs.jpa.hibernate.ddl-auto=none


# Mpi DataSource (PostgreSQL for mpi_patient)
spring.datasource.mpi.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.mpi.username=postgres
spring.datasource.mpi.password=pw
spring.datasource.mpi.driver-class-name=org.postgresql.Driver
spring.datasource.mpi.jpa.hibernate.ddl-auto=none


#Syncer DataSource (MSSQL)
spring.datasource.syncer.url=jdbc:sqlserver://18.208.216.140:1434;databaseName=MASTER;encrypt=true;trustServerCertificate=true;
spring.datasource.syncer.username=sa
spring.datasource.syncer.password=P@ssw0rd
spring.datasource.syncer.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.syncer.jpa.hibernate.ddl-auto=update






