version: '3.7'
services:
  jwtgenerator:
    image: jwtgenerator
    ports:
      - "8000:8000"
    networks:
      - apps_network

networks:
  apps_network:
      external:
        name: adapter_network



