apiVersion: v1

kind: ConfigMap
metadata:
  name: jwtgenerator-config
data:
  jwt_secret_for_algorithm: "once upon a time there lived a king, he wanted to build stairway to moon, i wonder is that possible?"
  jwt_claim_name: "Enquizit Inc"
  jwt_claim_email: "nbsmoderization@enquizit.com"
  jwt_claim_subject: "NBS Mederization"
  jwt_seed: "monroe"

