apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: jwtgenerator
  name: jwtgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwtgenerator
  template:
    metadata:
      labels:
        app: jwtgenerator
    spec:
      containers:
      - name: jwtgenerator
        imagePullPolicy: IfNotPresent
        image: jwtgenerator
        ports:
          - containerPort: 8000
        env:
          - name: HASHIVAULT_ENABLED
            value: "false"
          - name: JWT_SECRETFORALGORITHM
            valueFrom:
              configMapKeyRef:
                name: jwtgenerator-config
                key: jwt_secret_for_algorithm
          - name: JWT_CLAIMNAME
            valueFrom:
              configMapKeyRef:
                name: jwtgenerator-config
                key: jwt_claim_name
          - name: JWT_CLAIMEMAIL
            valueFrom:
              configMapKeyRef:
                name: jwtgenerator-config
                key: jwt_claim_email
          - name: JWT_CLAIMSUBJECT
            valueFrom:
              configMapKeyRef:
                name: jwtgenerator-config
                key: jwt_claim_subject
          - name: JWT_SEED
            valueFrom:
              configMapKeyRef:
                name: jwtgenerator-config
                key: jwt_seed

