name: Build and push data-ingestion-service and data-processing-service images to ECR
on:
  push:
    branches:
      - main
      - master
      - rel-**
    paths:
      - "data-ingestion-service/**"
      - "data-processing-service/**"
      - "cdaschema/**"
      - "hl7-parser/**"
      - "srte-data-service/**"
      - "phdc-xsd-jaxb/**"
jobs:
  sonar_scan:
    uses: ./.github/workflows/sonar.yaml
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      PASSED_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  call-build-microservice-container-workflow:
    permissions:
      id-token: write
      contents: read
      security-events: write
    name: Build Container
    needs: sonar_scan
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: data-ingestion-service
      dockerfile_relative_path: -f ./data-ingestion-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "21"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-update-helm-data-ingestion:
    permissions:
      id-token: write
      contents: write      
      pull-requests: write
    name: Request DEV deployment
    needs: call-build-microservice-container-workflow
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: data-ingestion-service
      values_file_with_path: charts/dataingestion-service/values-dts1.yaml
      new_image_tag: ${{ needs.call-build-microservice-container-workflow.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-build-dataprocessing-microservice-container-workflow:
    permissions:
      id-token: write
      contents: read
      security-events: write
    name: Build Container
    needs: sonar_scan
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: data-processing-service
      dockerfile_relative_path: -f ./data-processing-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "21"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-update-helm-dataprocessing:
    permissions:
      id-token: write
      contents: write      
      pull-requests: write
    name: Request DEV deployment
    needs: call-build-dataprocessing-microservice-container-workflow
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: data-processing-service
      values_file_with_path: charts/data-processing-service/values-dts1.yaml
      new_image_tag: ${{ needs.call-build-dataprocessing-microservice-container-workflow.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-build-srte-data-service-microservice-container-workflow:
    permissions:
      id-token: write
      contents: read
      security-events: write
    name: Build Container
    #    needs: sonar_scan
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: srte-data-service
      dockerfile_relative_path: -f ./srte-data-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "21"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-update-helm-srte-data-service:
    name: Request DEV deployment
    needs: call-build-srte-data-service-microservice-container-workflow
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: srte-data-service
      values_file_with_path: charts/srte-data-service/values-dts1.yaml
      new_image_tag: ${{ needs.call-build-srte-data-service-microservice-container-workflow.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}
