name: Build and push data-ingestion-service image to ECR
on:
  push:
    branches:
      - main
      - master
      - rel-**
      - CNDIT-640-github-**
    paths-ignore:
      - "docker-compose.yml"
      - "**.md"
jobs:
  sonar_scan:
    uses: ./.github/workflows/sonar.yaml
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      PASSED_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  call-build-microservice-container-workflow:
    name: Build Container
    needs: sonar_scan
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: data-ingestion-service
      dockerfile_relative_path: -f ./report-service/Dockerfile .
      environment_classifier: SNAPSHOT
      java_version: "17"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}