name: Run tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Gradle packages
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'

    - name: Run all tests
      run: ./gradlew clean test

    - name: Publish Testing Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: all-test-reports
        # The '**' tells GitHub to look in every sub-folder for reports
        path: "**/build/reports/**"